.TH A 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
a \- Routines to print general error messages
.SH PURPOSE
These routines are meant to provide an easy way of printing error messages
prior to function and process termination.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIa_print_abort\fP 1i
Print an abort message.
.IP \fIa_prog_bug\fP 1i
Print a bug message.
.IP \fIa_func_abort\fP 1i
Print a warning message.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
