.TH A_PRINT_ABORT 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
a_print_abort \- Print an abort message.
.SH SYNOPSIS
.B #include <karma_a.h>
.sp
.B void a_print_abort
.sp
()
.SH DESCRIPTION
This routine will print the message "Aborting.\n" to the standard
error and will then abort the process.
.SH RETURN VALUE
The routine does not return. The process is aborted.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
