.TH C_LIST_TEST_EMPTY 3 "07 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
c_list_test_empty \- Test if a callback list has any callbacks registered with it.
.SH SYNOPSIS
.B #include <karma_c.h>
.sp
.B flag c_list_test_empty
.sp
(KCallbackList list)
.SH DESCRIPTION
Test if a callback list has any callbacks registered with it.
.IP \fIlist\fP 1i
The callback list.
.SH RETURN VALUE
TRUE if the list is empty (no callbacks), else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
