.TH C_UNREGISTER_CALLBACK2 3 "07 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
c_unregister_callback2 \- Unregister a callback function.
.SH SYNOPSIS
.B #include <karma_c.h>
.sp
.B void c_unregister_callback2
.sp
(KCallbackFunc callback)
.SH DESCRIPTION
Unregister a callback function.
.IP \fIcallback\fP 1i
The callback function. If this is NULL, nothing is done.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
