.TH C_WRITE_NULL_FUNC 3 "07 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
c_write_null_func \- Write NULL to a pointer.
.SH SYNOPSIS
.B #include <karma_c.h>
.sp
.B void c_write_null_func
.sp
(void **pointer)
.SH DESCRIPTION
Write NULL to a pointer.
.IP \fIpointer\fP 1i
The pointer to write NULL to.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
