.TH CANVAS_DRAW_LINES_P 3 "07 Aug 2006" "Karma Distribution"
.SH FUNCTION
canvas_draw_lines_p \- Draw multiple connected lines onto a world canvas.
.SH SYNOPSIS
.B #include <karma_canvas.h>
.sp
.B void canvas_draw_lines_p
.sp
(KWorldCanvas canvas,
CONST double *x_array, CONST double *y_array,
int num_points, unsigned long pixel_value)
.SH DESCRIPTION
Draw multiple connected lines onto a world canvas.
.IP \fIcanvas\fP 1i
The world canvas object.
.IP \fIx_array\fP 1i
The horizontal world co-ordinates of the points. If this is NULL,
the routine assumes horizontal co-ordinates equally spaced across the world
canvas.
.IP \fIy_array\fP 1i
The vertical world co-ordinates of the points. If this is NULL,
the routine assumes vertical co-ordinates equally spaced across the world
canvas.
.IP \fInum_points\fP 1i
The number of points. The number of lines drawn is 1 less than
this value.
.IP \fIpixel_value\fP 1i
The pixel value to use.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
