.TH CANVAS_TRACK_COMPUTE 3 "07 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
canvas_track_compute \- Compute track strings.
.SH SYNOPSIS
.B #include <karma_canvas.h>
.sp
.B void canvas_track_compute
.sp
(KWorldCanvas canvas, double x, double y,
double x_lin, double y_lin,
char world_string[STRING_LENGTH],
char extra_string[STRING_LENGTH])
.SH DESCRIPTION
Compute track strings.
.IP \fIcanvas\fP 1i
The world canvas.
.IP \fIx\fP 1i
The horizontal world co-ordinate of the event.
.IP \fIy\fP 1i
The vertical world co-ordinate of the event.
.IP \fIx_lin\fP 1i
The horizontal linear co-ordinate.
.IP \fIy_lin\fP 1i
The vertical linear co-ordinate.
.IP \fIworld_string\fP 1i
The world co-ordinates and restriction information will be
written here.
.IP \fIextra_string\fP 1i
Extra information is written here. This may be NULL if
<<world_string>> is also NULL.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
