.TH CANVAS_ASSOCIATE_OBJECT 3 "07 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
canvas_associate_object \- Associate an object with a world canvas.
.SH SYNOPSIS
.B #include <karma_canvas.h>
.sp
.B void canvas_associate_object
.sp
(KWorldCanvas canvas, CONST void *key,
CONST void *object, flag replace)
.SH DESCRIPTION
Associate an object with a world canvas.
.IP \fIcanvas\fP 1i
The world canvas.
.IP \fIkey\fP 1i
The key for the associated data object.
.IP \fIobject\fP 1i
The object pointer.
.IP \fIflag\fP 1i
If TRUE, an existing object with the same key is replaced.
.SH RETURN VALUE
Nothing. On failure, the process aborts.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
