.TH CANVAS_PROTO_DESTROY_FUNC 3 "07 Aug 2006" "Karma Distribution"
.SH PROTO_FUNC
canvas_PROTO_destroy_func \- Process a destroy event on a world canvas.
.SH SYNOPSIS
.B #include <karma_canvas.h>
.sp
.B void canvas_PROTO_destroy_func
.sp
(void *info)
.SH DESCRIPTION
Process a destroy event on a world canvas.
.IP \fIinfo\fP 1i
An arbitrary function information pointer.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
