.TH CANVAS_REGISTER_REFRESH_FUNC 3 "07 Aug 2006" "Karma Distribution"
.SH FUNCTION
canvas_register_refresh_func \- Register world canvas refresh callback.
.SH SYNOPSIS
.B #include <karma_canvas.h>
.sp
.B KCallbackFunc canvas_register_refresh_func
.sp
(KWorldCanvas canvas,
void (*refresh_func) (),void *info)
.SH DESCRIPTION
This routine will register a refresh function for a world canvas.
The refresh function will be called whenever the contents of the canvas
need to be redrawn. Many refresh functions may be registered per canvas.
The first function registered is the first function called upon refresh.
.IP \fIcanvas\fP 1i
The world canvas.
.IP \fIrefresh_func\fP 1i
The function that is called when the canvas is to be
refreshed. The prototype function is <-canvas_PROTO_refresh_func->.
.IP \fIinfo\fP 1i
The initial arbitrary canvas information pointer.
.SH RETURN VALUE
A KCallbackFunc object.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
