.TH CANVAS_DRAW_DRESSING 3 "07 Aug 2006" "Karma Distribution"
.SH FUNCTION
canvas_draw_dressing \- Draw the dressing (axes, etc.) for a world canvas.
.SH SYNOPSIS
.B #include <karma_canvas.h>
.sp
.B void canvas_draw_dressing
.sp
(KWorldCanvas canvas)
.SH DESCRIPTION
Draw the dressing (axes, etc.) for a world canvas.
.IP \fIcanvas\fP 1i
The world canvas object.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH NOTE
This routine is called automatically each time the canvas is
refreshed.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
