.TH CH_CREATE_ZERO 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ch_create_zero \- Create data source.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B Channel ch_create_zero
.sp
()
.SH DESCRIPTION
This routine will create a data source channel. All reads from
the channel will yield values of zero. Write operations fail.
.SH RETURN VALUE
The channel object on succes, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
