.TH CH_CLOSE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ch_close \- Close a channel.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B flag ch_close
.sp
(Channel channel)
.SH DESCRIPTION
This routine will close a channel object. The write buffer will
be flushed prior to closure.
.IP \fIchannel\fP 1i
The channel object.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
