.TH CH_DRAIN 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ch_drain \- Drain bytes from a channel.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B unsigned int ch_drain
.sp
(Channel channel, unsigned int length)
.SH DESCRIPTION
This routine will drain (read) a specified number of bytes from a
channel, ignoring the data.
.IP \fIchannel\fP 1i
The Channel object.
.IP \fIlength\fP 1i
The number of bytes to drain.
.SH RETURN VALUE
The number of bytes drained.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
