.TH CH_GET_MMAP_ADDR 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ch_get_mmap_addr \- Get memory mapped address.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B char * ch_get_mmap_addr
.sp
(Channel channel)
.SH DESCRIPTION
This routine will get the starting address of the data for a
memory mapped disc channel. The channel MUST be a memory mapped disc
channel.
.IP \fIchannel\fP 1i
The channel object.
.SH RETURN VALUE
The address of the memory mapped data.
.SH Multi-threading Level
Unsafe.
.SH NOTE
If the memory mapped address space is read-only, any attempt to
write to this address space will cause a segmentation fault.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
