.TH CH_PROTO_CONVERTER_CLOSE_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
ch_PROTO_converter_close_func \- Close.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B void ch_PROTO_converter_close_func
.sp
(void *info, Channel channel)
.SH DESCRIPTION
This routine is called when a channel is closed.
.IP \fIinfo\fP 1i
The arbitrary information pointer.
.IP \fIchannel\fP 1i
The channel object.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
