.TH CH_PROTO_CLOSE_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
ch_PROTO_close_func \- Process a destroy event for an object.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B flag ch_PROTO_close_func
.sp
(void *info)
.SH DESCRIPTION
Process a destroy event for an object.
.IP \fIinfo\fP 1i
An arbitrary function information pointer.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
