.TH CH_READ_AND_SWAP_BLOCKS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ch_read_and_swap_blocks \- Read blocks from a channel and swap bytes.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B uaddr ch_read_and_swap_blocks
.sp
(Channel channel, char *buffer,
uaddr num_blocks, uaddr block_size)
.SH DESCRIPTION
This routine will read a number of blocks from a channel and
places them into a buffer after swapping (reversing the order).
.IP \fIchannel\fP 1i
The channel object.
.IP \fIbuffer\fP 1i
The buffer to write the data into.
.IP \fInum_blocks\fP 1i
The number of blocks to read.
.IP \fIblock_size\fP 1i
The size (in bytes) of each block.
.SH RETURN VALUE
The number of bytes read. Errors may cause partial blocks to be
read.
.SH Multi-threading Level
Unsafe.
.SH NOTE
If the channel is a connection and the number of bytes readable from
the connection is equal to or more than <<num_blocks * block_size>> the
routine will NOT block.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
