.TH CH_SWAP_AND_WRITE_BLOCKS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ch_swap_and_write_blocks \- Write blocks to a channel after swapping bytes.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B uaddr ch_swap_and_write_blocks
.sp
(Channel channel, CONST char *buffer,
uaddr num_blocks, uaddr block_size)
.SH DESCRIPTION
This routine will write a number of blocks to a channel after
swapping the bytes.
.IP \fIchannel\fP 1i
The channel object.
.IP \fIbuffer\fP 1i
The buffer to read the data from.
.IP \fInum_blocks\fP 1i
The number of blocks to write.
.IP \fIblock_size\fP 1i
The size (in bytes) of each block.
.SH RETURN VALUE
The number of bytes written. Errors may cause partial blocks to
be written.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
