.TH CH_SKIP 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ch_skip \- Skip bytes in a channel, seeking if possible.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B flag ch_skip
.sp
(Channel channel, uaddr num_bytes)
.SH DESCRIPTION
This function will skip a specified number of bytes in a channel,
jumping to the desired point without reading (if possible). If the channel
does not support seeking (jumping), then the specified number of bytes are
read from the channel.
.IP \fIchannel\fP 1i
The channel object.
.IP \fInum_bytes\fP 1i
The number of bytes to skip.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH NOTE
Seeking may change the write pointer. Use <-ch_drain-> instead if
the write pointer must be left untouched.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
