.TH CH_SET_BUFFER_SIZES 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ch_set_buffer_sizes \- Set the read and write buffer sizes for a channel.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B flag ch_set_buffer_sizes
.sp
(Channel channel, unsigned long read_size,
unsigned long write_size)
.SH DESCRIPTION
Set the read and write buffer sizes for a channel.
.IP \fIchannel\fP 1i
The channel object.
.IP \fIread_size\fP 1i
The read buffer size.
.IP \fIwrite_size\fP 1i
The write buffer size.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
