.TH CH_TEST_FOR_CONNECTION 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ch_test_for_connection \- Test if a channel object is a connection channel.
.SH SYNOPSIS
.B #include <karma_ch.h>
.sp
.B flag ch_test_for_connection
.sp
(Channel channel)
.SH DESCRIPTION
Test if a channel object is a connection channel.
.IP \fIchannel\fP 1i
The channel object.
.SH RETURN VALUE
TRUE if the channel object is a connection, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
