.TH CHS 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
chs \- Routines to scan values from channel objects
.SH PURPOSE
These routines are meant to provide a simple method of reading (scanning)
channel objects for ASCII representations of floating point and integer
values.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIchs_get_value\fP 1i
Scan a channel object for a whitespace separated value.
.IP \fIchs_get_value2\fP 1i
Scan a channel object for a whitespace separated value.
.IP \fIchs_get_float\fP 1i
Scan a channel object for a float value.
.IP \fIchs_get_int\fP 1i
Scan a channel object for an integer value.
.IP \fIchs_get_line\fP 1i
Scan a channel object for a line.
.IP \fIchs_get_line2\fP 1i
Scan a channel object for a line.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
