.TH CM_UNMANAGE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
cm_unmanage \- Terminate the management of a child process for state changes.
.SH SYNOPSIS
.B #include <karma_cm.h>
.sp
.B void cm_unmanage
.sp
(int pid)
.SH DESCRIPTION
Terminate the management of a child process for state changes.
.IP \fIpid\fP 1i
The ID of the child process to unmanage.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
