.TH COL 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
col \- Routines to convert between colour spaces
.SH PURPOSE
These routines are meant to provide basic conversions between colours in
different colour spaces.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIcol_hsb_slice_to_rgb_array\fP 1i
Generate a table of RGB values from a slice of HSB space.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
