.TH CONN_PROTO_QUIESCENT_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
conn_PROTO_quiescent_func \- Quiescence callback.
.SH SYNOPSIS
.B #include <karma_conn.h>
.sp
.B void conn_PROTO_quiescent_func
.sp
()
.SH DESCRIPTION
This routine is called when the Connection Management tool or
shell is quiescent.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
