.TH CONN_INITIALISE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
conn_initialise \- Initialise the package.
.SH SYNOPSIS
.B #include <karma_conn.h>
.sp
.B void conn_initialise
.sp
( void (*exit_schedule_func) () )
.SH DESCRIPTION
Initialise the package.
.IP \fIexit_shedule_func\fP 1i
The routine which should be called when a clean exit is
to be scheduled. The prototype function is
<-conn_PROTO_exit_schedule_func->.
If this is NULL, then exit(3) is called instead.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH NOTE
This routine MUST be called prior to the <-conn_become_server->
routine.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
