.TH CONN_CONTROLLED_BY_CM_TOOL 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
conn_controlled_by_cm_tool \- Check if controlled by CM tool.
.SH SYNOPSIS
.B #include <karma_conn.h>
.sp
.B flag conn_controlled_by_cm_tool
.sp
()
.SH DESCRIPTION
This routine will determine if the module is being controlled by
the Connection Management tool.
.SH RETURN VALUE
TRUE if the module is controlled, else FALSE
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
