.TH CONSTRUCT 3 "13 Aug 2006" "Karma Distribution"
.SH PACKAGE
construct \- Routines to manage construction of data
.SH PURPOSE
These routines are meant to provide a high level mechanism to manage the
construction of data.
NOTE: THIS PACKAGE IS WORK IN PROGRESS. THE INTERFACE MAY CHANGE IN THE
NEXT RELEASE, POSSIBLY WITHOUT NOTICE.
.SH LIBRARY
karmagraphics
.SH LINK WITH
-lkarmagraphics
.SH FUNCTIONS
.IP \fIconstruct_array_list_algorithms\fP 1i
List available algorithms.
.IP \fIconstruct_array_create_manager\fP 1i
Create a management object for creating array data.
.IP \fIconstruct_array_destroy_manager\fP 1i
Destroy a management object for creating array data.
.IP \fIconstruct_array_select_algorithm\fP 1i
Select an algorithm for constructing data.
.IP \fIconstruct_array_change_name\fP 1i
Change the default output name for constructed data.
.IP \fIconstruct_array_create_data\fP 1i
Construct an array.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
