.TH CONSTRUCT_ARRAY_LIST_ALGORITHMS 3 "13 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
construct_array_list_algorithms \- List available algorithms.
.SH SYNOPSIS
.B #include <karma_construct.h>
.sp
.B CONST char ** construct_array_list_algorithms
.sp
(unsigned int *num_algorithms)
.SH DESCRIPTION
List available algorithms.
.IP \fInum_algorithms\fP 1i
The number of available algorithms is written here.
.SH RETURN VALUE
A pointer to the list of algorithm names.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
