.TH CONSTRUCT_ARRAY_DESTROY_MANAGER 3 "13 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
construct_array_destroy_manager \- Destroy a management object for creating array data.
.SH SYNOPSIS
.B #include <karma_construct.h>
.sp
.B void construct_array_destroy_manager
.sp
(KConstructArrayManager manager)
.SH DESCRIPTION
Destroy a management object for creating array data.
.IP \fImanager\fP 1i
The management object.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
