.TH CONTOUR_DESTROY_GROUP 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
contour_destroy_group \- Destroy a group of KContourImage objects.
.SH SYNOPSIS
.B #include <karma_contour.h>
.sp
.B void contour_destroy_group
.sp
(KContourImageGroup group)
.SH DESCRIPTION
Destroy a group of KContourImage objects.
.IP \fIgroup\fP 1i
The group to destroy. The group container is also destroyed.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
