.TH CONTOUR_CREATE_VIEWABLE_GROUP 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
contour_create_viewable_group \- Create container to hold group of KViewableContourImage objects.
.SH SYNOPSIS
.B #include <karma_contour.h>
.sp
.B KViewableContourImageGroup contour_create_viewable_group
.sp
()
.SH DESCRIPTION
Create container to hold group of KViewableContourImage objects.
.SH RETURN VALUE
The group container on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
