.TH D_ENTER_DAEMON_MODE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
d_enter_daemon_mode \- Enter daemon mode.
.SH SYNOPSIS
.B #include <karma_d.h>
.sp
.B void d_enter_daemon_mode
.sp
()
.SH DESCRIPTION
This routine will cause the module to enter daemon mode. This
involves detatching from a terminal.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
