.TH D_TEST_DAEMON_MODE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
d_test_daemon_mode \- Test if the module is running in daemon mode.
.SH SYNOPSIS
.B #include <karma_d.h>
.sp
.B flag d_test_daemon_mode
.sp
()
.SH DESCRIPTION
Test if the module is running in daemon mode.
.SH RETURN VALUE
TRUE if the module is running in daemon mode, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
