.TH DIR_CLOSE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
dir_close \- Close a directory.
.SH SYNOPSIS
.B #include <karma_dir.h>
.sp
.B void dir_close
.sp
(KDir dir)
.SH DESCRIPTION
Close a directory.
.IP \fIdir\fP 1i
The directory object.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
