.TH DISPDATA_GET_DATACLASS_ATTRIBUTES 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_dataclass_attributes \- Get global attributes for the a dataclass.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B void dispdata_get_dataclass_attributes
.sp
(KDisplayDataClass dataclass, ...)
.SH DESCRIPTION
Get global attributes for the a dataclass.
.IP \fIdataclass\fP 1i
The KDisplayDataClass the attributes are destined for.
.IP \fI...\fP 1i
The optional attributes are given as pairs of attribute-key
attribute-value pairs. This list must be terminated with
KDISPLAYDATA_CLASS_ATT_END.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
