.TH DISPDATA_TEST_BLINKSTATE_ACTIVE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_test_blinkstate_active \- Test if blinkstate is the active one for its window.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B flag dispdata_test_blinkstate_active
.sp
(KDisplayDataBlinkState blinkstate)
.SH DESCRIPTION
Test if blinkstate is the active one for its window.
.IP \fIblinkstate\fP 1i
The KDisplayDataBlinkState object.
.SH RETURN VALUE
TRUE if active, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
