.TH DISPDATA_GET_BLINKSTATE_INDEX 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_blinkstate_index \- Get the index for a blinkstate.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B unsigned int dispdata_get_blinkstate_index
.sp
(KDisplayDataBlinkState blinkstate)
.SH DESCRIPTION
Get the index for a blinkstate.
.IP \fIblinkstate\fP 1i
The KDisplayDataBlinkState object.
.SH RETURN VALUE
The index of the blinkstate.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
