.TH DISPDATA_GET_DATAOBJECT_FROM_BLINKENTRY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_dataobject_from_blinkentry \- Get the dataobject for a blinkentry.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B KDisplayDataObject dispdata_get_dataobject_from_blinkentry
.sp
(KDisplayDataBlinkEntry blinkentry)
.SH DESCRIPTION
Get the dataobject for a blinkentry.
.IP \fIblinkentry\fP 1i
The blinkentry.
.SH RETURN VALUE
The dataobject.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
