.TH DISPDATA_GET_NEXT_BLINKENTRY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_next_blinkentry \- Get the next blink entry after a specified entry.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B KDisplayDataBlinkEntry dispdata_get_next_blinkentry
.sp
(KDisplayDataBlinkEntry blinkentry)
.SH DESCRIPTION
Get the next blink entry after a specified entry.
.IP \fIblinkentry\fP 1i
The KDisplayDataBlinkEntry object.
.SH RETURN VALUE
A KDisplayDataBlinkEntry object. NULL may be returned if there
are no more blink state entries.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
