.TH DISPDATA_REFRESH_BLINKSTATE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_refresh_blinkstate \- Refresh the user interface for a blink state.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B void dispdata_refresh_blinkstate
.sp
(KDisplayDataBlinkState blinkstate)
.SH DESCRIPTION
Refresh the user interface for a blink state.
.IP \fIblinkstate\fP 1i
The blink state to refresh.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
