.TH DISPDATA_GET_BLINKSTATE_INFO 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_blinkstate_info \- Get the arbitrary pointer for a blinkstate.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B void * dispdata_get_blinkstate_info
.sp
(KDisplayDataBlinkState blinkstate)
.SH DESCRIPTION
Get the arbitrary pointer for a blinkstate.
.IP \fIblinkstate\fP 1i
The blinkstate.
.SH RETURN VALUE
The arbitrary pointer.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
