.TH DISPDATA_GET_FIRST_DATAOBJECT 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_first_dataobject \- Get first data object for a dataclass.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B KDisplayDataObject dispdata_get_first_dataobject
.sp
(KDisplayDataClass dataclass)
.SH DESCRIPTION
Get first data object for a dataclass.
.IP \fIdataclass\fP 1i
The KDisplayDataClass the data belong to.
.SH RETURN VALUE
A KDisplayDataObject object. NULL is returned if there are no
dataobjects.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
