.TH DISPDATA_GET_WINDOW_FROM_BLINKSTATE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_window_from_blinkstate \- Get the windor for a blinkstate.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B KDisplayDataWindow dispdata_get_window_from_blinkstate
.sp
(KDisplayDataBlinkState blinkstate)
.SH DESCRIPTION
Get the windor for a blinkstate.
.IP \fIblinkstate\fP 1i
The blinkstate.
.SH RETURN VALUE
The window.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
