.TH DISPDATA_ARRAY_CREATE_DATACLASS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_array_create_dataclass \- Initialise array data support for the package.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B KDisplayDataClass dispdata_array_create_dataclass
.sp
(void)
.SH DESCRIPTION
Initialise array data support for the package.
.SH RETURN VALUE
A KDisplayDataClass object on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
