.TH DISPDATA_REFRESH_WINDOW 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_refresh_window \- Refresh a window.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B void dispdata_refresh_window
.sp
(KDisplayDataWindow window, KWorldCanvas canvas)
.SH DESCRIPTION
Refresh a window.
.IP \fIwindow\fP 1i
The KDisplayDataWindow object to refresh.
.IP \fIcanvas\fP 1i
The preferred KWorldCanvas to display. This may be NULL.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
