.TH DISPDATA_GET_NAMELIST 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_namelist \- Get the list of (sorted) data names for a dataclass.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B CONST char ** dispdata_get_namelist
.sp
(KDisplayDataClass dataclass,
unsigned int *num_entries,
unsigned int *num_chars)
.SH DESCRIPTION
Get the list of (sorted) data names for a dataclass.
.IP \fIdataclass\fP 1i
The KDisplayDataClass object.
.IP \fInum_entries\fP 1i
The number of entries in the list is written here.
.IP \fInum_chars\fP 1i
The sum of the lengths of the names is written here. This does
not include terminator characters.
.SH RETURN VALUE
The array of names.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
