.TH DISPDATA_GET_LAST_BLINKSTATE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dispdata_get_last_blinkstate \- Get last blinkstate for a window.
.SH SYNOPSIS
.B #include <karma_dispdata.h>
.sp
.B KDisplayDataBlinkState dispdata_get_last_blinkstate
.sp
(KDisplayDataWindow window,
void **info)
.SH DESCRIPTION
Get last blinkstate for a window.
.IP \fIwindow\fP 1i
The window.
.IP \fIinfo\fP 1i
The arbitrary information pointer is written here. If this is NULL,
nothing is written here.
.SH RETURN VALUE
A KDisplayDataBlinkState object. NULL is returned if there are no
blinkstates associated with this window.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
