.TH DL_CLOSE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dl_close \- Close a loaded object.
.SH SYNOPSIS
.B #include <karma_dl.h>
.sp
.B int dl_close
.sp
(void *handle)
.SH DESCRIPTION
Close a loaded object.
.IP \fIhandle\fP 1i
A handle to the loaded object.
.SH RETURN VALUE
0 on success, else non-zero on error.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
