.TH DM_NATIVE_POLL 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dm_native_poll \- Poll all managed descriptors for any activity.
.SH SYNOPSIS
.B #include <karma_dm.h>
.sp
.B void dm_native_poll
.sp
(long timeout_ms)
.SH DESCRIPTION
Poll all managed descriptors for any activity.
.IP \fItimeout_ms\fP 1i
The time (in milliseconds) to poll. If this is less than 0
the routine will poll forever (until some activity occurs or a signal is
caught).
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
