.TH DM_NATIVE_GET_IDLE_TIME 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dm_native_get_idle_time \- Get the idle time in microseconds.
.SH SYNOPSIS
.B #include <karma_dm.h>
.sp
.B unsigned long dm_native_get_idle_time
.sp
()
.SH DESCRIPTION
Get the idle time in microseconds.
.SH RETURN VALUE
The idle time.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
