.TH DM_NATIVE_SETUP 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dm_native_setup \- Setup descriptor management using native implementation.
.SH SYNOPSIS
.B #include <karma_dm.h>
.sp
.B void dm_native_setup
.sp
()
.SH DESCRIPTION
Setup descriptor management using native implementation.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
