.TH DMP 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
dmp \- Routines to dump an ASCII representation of a data structure
.SH PURPOSE
These routines are meant to provide a mechanism for writing the recursive,
heirarchical data structure to a file in an ASCII (human readable) format.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIdmp_multi_desc\fP 1i
Dump a multi_array descriptor to a file.
.IP \fIdmp_packet_desc\fP 1i
Dump a packet descriptor to a file.
.IP \fIdmp_element_desc\fP 1i
Dump an element descriptor to a file.
.IP \fIdmp_array_desc\fP 1i
Dump an array descriptor to a file.
.IP \fIdmp_dim_desc\fP 1i
Dump a dimension descriptor to a file.
.IP \fIdmp_multi_data\fP 1i
Dump the data in a multi_array descriptor to a file.
.IP \fIdmp_packet\fP 1i
Dump a packet to a file.
.IP \fIdmp_element\fP 1i
Dump an element to a file.
.IP \fIdmp_array\fP 1i
Dump an array to a file.
.IP \fIdmp_list\fP 1i
Dump a linked list to a file.
.IP \fIdmp_flag\fP 1i
Dump a flag value to a file.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
