.TH DMX 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
dmx \- Routines to manage file descriptors using the Xt toolkit
.SH PURPOSE
These routines provide an interface between the descriptor management
facility (ie. event processing on pipes, connections and terminals)
available with the <-dm-> package and the Xt toolkit event handler.
NOTE: THIS PACKAGE IS WORK IN PROGRESS. THE INTERFACE MAY CHANGE IN THE
NEXT RELEASE, POSSIBLY WITHOUT NOTICE.
.SH LIBRARY
karmaXt
.SH LINK WITH
-lkarmaXt
.SH FUNCTIONS
.IP \fIdmx_register_app_context\fP 1i
Register Xt application context for event management.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
