.TH DS_APPEND_DIM_DESC 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_append_dim_desc \- Append a dimension to an array.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_append_dim_desc
.sp
(array_desc *arr_desc, dim_desc *dimension)
.SH DESCRIPTION
This routine will append a dimension descriptor to the list of
dimensions attached to an array descriptor. The appended dimension will be
the LEAST significant dimension (co-ordinates have lowest stride). Tiling
information is preserved, however, any address offset information is
removed. If the array is NOT tiled, the dimension length will be copied
into the array of bottom tile lengths.
.IP \fIarr_desc\fP 1i
The array descriptor.
.IP \fIdimension\fP 1i
The dimension descriptor.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
