.TH DS_ALLOC_PACKET_DESC 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_alloc_packet_desc \- Allocate a packet descriptor.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B packet_desc * ds_alloc_packet_desc
.sp
(unsigned int num_elem)
.SH DESCRIPTION
This routine will allocate a packet descriptor. The memory for
the array of element types and descriptors is also allocated.
.IP \fInum_elem\fP 1i
The number of elements to allocate.
.SH RETURN VALUE
A pointer to the descriptor on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
