.TH DS_CAN_SWAPTRANSFER_ELEMENT 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_can_swaptransfer_element \- Test if an element can be swapped and transferred in one block.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_can_swaptransfer_element
.sp
(unsigned int type)
.SH DESCRIPTION
This routine will determine if an element can be transferred as a
single block of data with swapping (i.e. no extra conversion other than
byte-swapping between host and network format is needed).
.IP \fItype\fP 1i
The type of the element.
.SH RETURN VALUE
TRUE if the element may be byteswapped and transferred in a
single block, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
