.TH DS_COMPARE_DIM_DESC 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_compare_dim_desc \- Compare two dimension descriptors.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_compare_dim_desc
.sp
(CONST dim_desc *desc1, CONST dim_desc *desc2)
.SH DESCRIPTION
Compare two dimension descriptors.
.IP \fIdesc1\fP 1i
One of the dimension descriptors.
.IP \fIdesc2\fP 1i
The other dimension descriptor.
.SH RETURN VALUE
TRUE if the two dimension descriptors are equal, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
