.TH DS_COPY_PACKET 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_copy_packet \- Copy a packet.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_copy_packet
.sp
(CONST packet_desc *pack_desc, char *dest_packet,
CONST char *source_packet)
.SH DESCRIPTION
Copy a packet.
.IP \fIpack_desc\fP 1i
The packet descriptor.
.IP \fIdest_packet\fP 1i
The destination packet data will be written here.
.IP \fIsource_packet\fP 1i
The source packet data.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH NOTE
The routine will copy only the data and pointers to arrays and
linked lists in the packet, not the arrays and linked lists which may be
pointed to.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
