.TH DS_CHECK_ARRAY_CAN_FIT 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ds_check_array_can_fit \- Check if the array data can fit in the machine.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_check_array_can_fit
.sp
(CONST array_desc *arr_desc)
.SH DESCRIPTION
Check if the array data can fit in the machine.
.IP \fIarr_desc\fP 1i
The array descriptor.
.SH RETURN VALUE
TRUE if the array may fit, otherwise FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
