.TH DS_DEALLOC_LIST_ENTRIES 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_dealloc_list_entries \- Recursively deallocate list entries.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B void ds_dealloc_list_entries
.sp
(CONST packet_desc *list_desc,
list_header *list_head)
.SH DESCRIPTION
This routine will deallocate all memory associated with the
storage of data in a linked list.
Any sub-arrays or linked lists are recursively deallocated.
The routine is quite robust, deallocating in the correct order and cleanly
bypassing missing sections in the hierarchy.
The list header is NOT deallocated.
.IP \fIlist_desc\fP 1i
The descriptor for the list.
.IP \fIlist_head\fP 1i
The linked list header.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
