.TH DS_DEALLOC_MULTI 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_dealloc_multi \- Deallocate a multi_array data structure.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B void ds_dealloc_multi
.sp
(multi_array *multi_desc)
.SH DESCRIPTION
This routine will deallocate all memory associated with a
multi_array header. This includes all the descriptors and data arrays and
lists in the hierarchy below. The routine will only deallocate the data
structure when it's attachment count is zero, else it decrements the
attachment count and returns. The routine is quite robust, deallocating in
the correct order and cleanly bypassing missing sections in the hierarchy.
.IP \fImulti_desc\fP 1i
The descriptor.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
