.TH DS_EVENT_DISPATCH 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
ds_event_dispatch \- Dispatch a multi_array event.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_event_dispatch
.sp
(multi_array *multi_desc,
CONST char *domain, CONST char *name)
.SH DESCRIPTION
Dispatch a multi_array event.
.IP \fImulti_desc\fP 1i
The multi_array descriptor.
.IP \fIdomain\fP 1i
The domain from where the event was generated.
.IP \fIname\fP 1i
The name of the event in its domain.
.SH RETURN VALUE
TRUE if one of the callbacks quenched the further delivery of
callbacks, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
