.TH DS_F_DIM_IN_ARRAY 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_f_dim_in_array \- Find dimension in array.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B unsigned int ds_f_dim_in_array
.sp
(CONST array_desc *arr_desc, CONST char *name)
.SH DESCRIPTION
Find dimension in array.
.IP \fIarr_desc\fP 1i
The array descriptor.
.IP \fIname\fP 1i
The name of the dimension to find. If this is NULL, then the routine
will not find anything.
.SH RETURN VALUE
The number of the dimension in the array if it was found, else
the number of dimensions in the array.
.SH Multi-threading Level
Unsafe.
.SH NOTE
If the specified name occurs twice, the program aborts.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
