.TH DS_GET_COORDINATE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_get_coordinate \- Get a co-ordinate along a dimension.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B double ds_get_coordinate
.sp
(CONST dim_desc *dimension, double coord_num)
.SH DESCRIPTION
Get a co-ordinate along a dimension.
.IP \fIdimension\fP 1i
The dimension descriptor.
.IP \fIcoord_num\fP 1i
The co-ordinate index.
.SH RETURN VALUE
The co-ordinate on success, else TOOBIG.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
