.TH DS_HISTORY_COPY 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_history_copy \- Copy history information.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_history_copy
.sp
(multi_array *out, CONST multi_array *in)
.SH DESCRIPTION
Copy history information.
.IP \fIout\fP 1i
The output multi_array descriptor to copy the history to.
.IP \fIin\fP 1i
The input multi_array descriptor to copy the history from.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
