.TH DS_LIST_APPEND 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_list_append \- Append an entry to a linked list.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B void ds_list_append
.sp
(list_header *list_head, list_entry *entry)
.SH DESCRIPTION
Append an entry to a linked list.
.IP \fIlist_head\fP 1i
The list header.
.IP \fIentry\fP 1i
The new list entry.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
