.TH DS_PUT_ELEMENTS 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_put_elements \- Convert array of double precision complex data to atomic data.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_put_elements
.sp
(char *data, unsigned int data_type,
unsigned int data_stride, double *values,
unsigned int num_values)
.SH DESCRIPTION
This routine will convert an array of double precision complex
values to an array of atomic data.
.IP \fIdata\fP 1i
The array of output data.
.IP \fIdata_type\fP 1i
The type of the data.
.IP \fIdata_stride\fP 1i
The stride of data elements in memory (in bytes).
.IP \fIvalues\fP 1i
The data values will be read from here.
.IP \fInum_values\fP 1i
The number of data values to convert.
.SH RETURN VALUE
TRUE if the data was successfully converted, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
