.TH DS_TRAVERSE_LIST 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ds_traverse_list \- Recursively traverse a pair of linked lists.
.SH SYNOPSIS
.B #include <karma_ds.h>
.sp
.B flag ds_traverse_list
.sp
( packet_desc *desc1, list_header *head1,
packet_desc *desc2, list_header *head2,
flag as_whole, flag (*func) () )
.SH DESCRIPTION
This routine will traverse a pair of linked lists and will
process a sub structure for every occurence wherever there is a difference
in the two data structures' descriptors.
.IP \fIdesc1\fP 1i
One of lists descriptor.
.IP \fIdata1\fP 1i
One of the lists header.
.IP \fIdesc2\fP 1i
The other lists descriptor.
.IP \fIdata2\fP 1i
The other lists header.
.IP \fIas_whole\fP 1i
If FALSE:
If the type or name of any element in the two packet descriptors are
different, the packets are deemed divergent and they are passed to
<<func>>.
If any aspect of the two array's dimension descriptors are different,
then the arrays are deemed divergent and their descriptors are passed
to <<func>>.
If TRUE:
If the type or name of any element in the two packet descriptors are
different, the packets are deemed divergent and they are passed to
<<func>>.
If any aspect of the two array's dimension descriptors are different,
or their packet descriptors are divergent, then the arrays are deemed
divergent and the array descriptors are passed to <<func>>.
If the packet descriptors for linked lists are divergent, then the two
lists are deemed divergent and their descriptors and headers are passed
to <<func>>.
.IP \fIfunc\fP 1i
The function to call for each divergence. The prototype function is
<-ds_PROTO_traverse_func->. If this returns FALSE, iterations are stopped.
.SH RETURN VALUE
TRUE if all iterations completed successfully, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
