.TH DSPROC 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
dsproc \- Routines to process named objects
.SH PURPOSE
These routines are meant to provide high level routines to process named
objects (i.e. disc and connection arrayfiles).
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIdsproc_object\fP 1i
Process a Karma file.
.IP \fIdsproc_multi_array\fP 1i
Process a Karma data structure.
.IP \fIdsproc_PROTO_pre_process\fP 1i
Perform pre-processing on a multi_array data structure.
.IP \fIdsproc_PROTO_process_array\fP 1i
Process a general data structure into an output structure.
.IP \fIdsproc_PROTO_post_process\fP 1i
Perform post-processing on a multi_array data structure.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
