.TH DSRA_DOUBLE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
dsra_double \- Read ASCII representation of a double floating point value.
.SH SYNOPSIS
.B #include <karma_dsra.h>
.sp
.B flag dsra_double
.sp
(Channel channel, double *value)
.SH DESCRIPTION
Read ASCII representation of a double floating point value.
.IP \fIchannel\fP 1i
The channel object to read from.
.IP \fIvalue\fP 1i
The result is written here.
.SH RETURN VALUE
TRUE if successful, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
