.TH DSRA_LIST 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
dsra_list \- Read ASCII represention of a linked list.
.SH SYNOPSIS
.B #include <karma_dsra.h>
.sp
.B flag dsra_list
.sp
(Channel channel, packet_desc *descriptor, list_header *header)
.SH DESCRIPTION
This routine will read in the ASCII representation of a linked
list of data from a channel object. The routine will recursively read in
sub arrays and linked lists.
.IP \fIchannel\fP 1i
The channel object to read from.
.IP \fIdescriptor\fP 1i
The descriptor for the list packets.
.IP \fIheader\fP 1i
The linked list header. This is modified. The linked list entries
will be contiguous in memory.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
