.TH DSRW_WRITE_LIST 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
dsrw_write_list \- Write a linked list in binary format.
.SH SYNOPSIS
.B #include <karma_dsrw.h>
.sp
.B flag dsrw_write_list
.sp
(Channel channel, CONST packet_desc *pack_desc,
CONST list_header *list_head)
.SH DESCRIPTION
This routine will write the binary representation of the data in
a linked list to a channel object. The routine will recursively write any
sub arrays or linked lists of packets.
.IP \fIchannel\fP 1i
The channel object.
.IP \fIpack_desc\fP 1i
The packet descriptor for the list entries.
.IP \fIlist_head\fP 1i
The linked list header.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
