.TH DSRW_WRITE_HISTORY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
dsrw_write_history \- Write history information.
.SH SYNOPSIS
.B #include <karma_dsrw.h>
.sp
.B flag dsrw_write_history
.sp
(Channel channel, CONST history *hist)
.SH DESCRIPTION
Write history information.
.IP \fIchannel\fP 1i
The channel to write to.
.IP \fIhist\fP 1i
A pointer to the first history entry.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
