.TH DSRW_READ_MULTI 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
dsrw_read_multi \- Read the binary representation of a multi_array structure.
.SH SYNOPSIS
.B #include <karma_dsrw.h>
.sp
.B multi_array * dsrw_read_multi
.sp
(Channel channel)
.SH DESCRIPTION
This routine will read the binary representation of a
multi_array general data structure header from a channel object and will
allocate the required descriptors. The routine will then read in the data
from the channel object and will write it into the data structure(s)
created.
.IP \fIchannel\fP 1i
The channel object.
.SH RETURN VALUE
A pointer to the multi array header on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
