.TH DSRW_READ_ARRAY_DESC 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
dsrw_read_array_desc \- Read the binary representation of an array descriptor.
.SH SYNOPSIS
.B #include <karma_dsrw.h>
.sp
.B array_desc * dsrw_read_array_desc
.sp
(Channel channel, unsigned int type)
.SH DESCRIPTION
This routine will read the binary representation of an array
descriptor from a channel object. The routine will recursively read the
packet descriptor for the array.
.IP \fIchannel\fP 1i
The channel object.
.IP \fItype\fP 1i
The type of the array. Legal values are:
ARRAYP   (old format)
K_ARRAY  (new format)
.SH RETURN VALUE
A pointer to the array descriptor on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
