.TH E_PROTO_EVENT_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
e_PROTO_event_func \- Event callback.
.SH SYNOPSIS
.B #include <karma_e.h>
.sp
.B flag e_PROTO_event_func
.sp
(KPeriodicEventFunc func, void *f_info, void *l_info)
.SH DESCRIPTION
This routine is called when a periodic event occurs.
.IP \fIfunc\fP 1i
The KPeriodicEventFunc object.
.IP \fIf_info\fP 1i
A pointer to arbitrary information for the function.
.IP \fIl_info\fP 1i
A pointer to arbitrary information for the event list.
.SH RETURN VALUE
TRUE if the event function should be called again, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
