.TH E_UNIX_DISPATCH_EVENTS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
e_unix_dispatch_events \- Dispatch events for Unix.
.SH SYNOPSIS
.B #include <karma_e.h>
.sp
.B void e_unix_dispatch_events
.sp
(unsigned int dispatch_level)
.SH DESCRIPTION
Dispatch events for Unix.
.IP \fIdispatch_level\fP 1i
The level of events that may dispatched. Event functions
at the same level or higher are dispatched.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
