.TH E_UNREGISTER_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
e_unregister_func \- Unregister an event function.
.SH SYNOPSIS
.B #include <karma_e.h>
.sp
.B void e_unregister_func
.sp
(KPeriodicEventFunc func)
.SH DESCRIPTION
Unregister an event function.
.IP \fIfunc\fP 1i
The callback function.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
