.TH EN 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
en \- Routines to provide encryption
.SH PURPOSE
These routines are meant to provide strong encryption.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIen_idea_init\fP 1i
Create stream for IDEA encryption.
.IP \fIen_idea_cfb\fP 1i
Encrypt bytes using the IDEA cipher.
.IP \fIen_idea_close\fP 1i
Close a cipher stream.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
