.TH EVENT_DISPATCH 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
event_dispatch \- Dispatch an event.
.SH SYNOPSIS
.B #include <karma_event.h>
.sp
.B void event_dispatch
.sp
(KEvent event)
.SH DESCRIPTION
Dispatch an event.
.IP \fIevent\fP 1i
The event.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
