.TH EX 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
ex \- Routines to extract data from strings
.SH PURPOSE
These routines are meant to provide a simple mechanism to extract numeric
values and strings from strings.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIex_int\fP 1i
Extract integer value from string.
.IP \fIex_uint\fP 1i
Extract unsigned integer value from string.
.IP \fIex_word\fP 1i
Extract word from string.
.IP \fIex_command\fP 1i
Extract command from string.
.IP \fIex_word_skip\fP 1i
Skip a word in a string.
.IP \fIex_float\fP 1i
Extract float value from string.
.IP \fIex_hour\fP 1i
Extract hour value from string.
.IP \fIex_command_skip\fP 1i
Skip a command in a string.
.IP \fIex_on\fP 1i
Extract boolean value from string.
.IP \fIex_on_or_off\fP 1i
Extract boolean value from string.
.IP \fIex_yes\fP 1i
Extract boolean value from string.
.IP \fIex_str\fP 1i
Extract sub-string from string.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
