.TH EX_WORD_SKIP 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
ex_word_skip \- Skip a word in a string.
.SH SYNOPSIS
.B #include <karma_ex.h>
.sp
.B CONST char * ex_word_skip
.sp
(CONST char *str)
.SH DESCRIPTION
Skip a word in a string.
.IP \fIstr\fP 1i
The string.
.SH RETURN VALUE
The next part of the string.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
