.TH EXIT_SCHEDULE_FUNC 3 "25 Nov 2000" "Karma Distribution"
.SH PROTO_FUNC
exit_schedule_func \- Exit schedule function.
.SH SYNOPSIS
.B #include <karma_conn.h>
.sp
.B void exit_schedule_func
.sp
()
.SH DESCRIPTION
This routine is called when the <-conn-> package wishes to
schedule a clean exit from the module.
This routine may return (ie. it need not exit).
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
