.TH FOREIGN_AIPS1_CLOSE_DATA_CONTEXT 3 "24 Dec 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
foreign_aips1_close_data_context \- Close a KAIPS1DataContext object.
.SH SYNOPSIS
.B #include <karma_foreign.h>
.sp
.B void foreign_aips1_close_data_context
.sp
(KAIPS1DataContext context)
.SH DESCRIPTION
Close a KAIPS1DataContext object.
.IP \fIcontext\fP 1i
The context.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
