.TH FOREIGN_FITS_WRITE_IARRAY 3 "24 Dec 2005" "Karma Distribution"
.SH FUNCTION
foreign_fits_write_iarray \- Write a FITS file to a channel.
.SH SYNOPSIS
.B #include <karma_foreign.h>
.sp
.B flag foreign_fits_write_iarray
.sp
(Channel channel, iarray array, ...)
.SH DESCRIPTION
This routine will write an Intelligent Array to a FITS file.
The routine will automatically generate essential keywords such as:
"NAXIS", "NAXISn", "CTYPEn", "CRVALn", "CRPIXn", "CDELTn", "BITPIX",
"BUNIT", "BSCALE" and "BZERO". Also, existing keywords in the data
structure which do not conflict with the generated keywords are copied.
.IP \fIchannel\fP 1i
The channel to write to. The channel is not flushed.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fI...\fP 1i
The optional attributes are given as pairs of attribute-key
attribute-value pairs. This list must be terminated with FA_FITS_WRITE_END.
See <-foreign_ATT_FITS_WRITE-> for a list of defined attributes.
.SH RETURN VALUE
TRUE on succes, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
