.TH FOREIGN_AIPS2_RUN 3 "24 Dec 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
foreign_aips2_run \- Fork and execute a programme.
.SH SYNOPSIS
.B #include <karma_foreign.h>
.sp
.B pid_t foreign_aips2_run
.sp
(CONST char *filename, int stdout_fd, int close_fd,
int *waitflags)
.SH DESCRIPTION
Fork and execute a programme.
.IP \fIfilename\fP 1i
The input filename for the programme.
.IP \fIstdout_fd\fP 1i
The output file descriptor.
.IP \fIclose_fd\fP 1i
The file descriptor to close.
.IP \fIwaitflags\fP 1i
Special flags to pass to waitpid(2) are written here.
.SH RETURN VALUE
The child process ID on success, else -1.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
