.TH FOREIGN_AIPS1_READ_HISTORY 3 "24 Dec 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
foreign_aips1_read_history \- Read history for an AIPS file.
.SH SYNOPSIS
.B #include <karma_foreign.h>
.sp
.B flag foreign_aips1_read_history
.sp
(KAIPS1DataContext context,
multi_array *multi_desc)
.SH DESCRIPTION
Read history for an AIPS file.
.IP \fIcontext\fP 1i
The context to read from.
.IP \fImulti_desc\fP 1i
The multi_array object to write the history to.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
