.TH GLS_INITIALISE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
gls_initialise \- Initialise Glish support.
.SH SYNOPSIS
.B #include <karma_gls.h>
.sp
.B flag gls_initialise
.sp
(int *argc, char **argv)
.SH DESCRIPTION
Initialise Glish support.
.IP \fIargc\fP 1i
As passed to the <<main>> function.
.IP \fIargv\fP 1i
As passed to the <<main>> function.
.SH RETURN VALUE
TRUE if running under Glish, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH NOTE
This function must not be called until the <-dm-> package is
initialised.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
