.TH GLS_TEST_RUNNING 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
gls_test_running \- Test if Glish available and running.
.SH SYNOPSIS
.B #include <karma_gls.h>
.sp
.B flag gls_test_running
.sp
()
.SH DESCRIPTION
Test if Glish available and running.
.SH RETURN VALUE
TRUE if Glish available and running, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
