.TH GRAPH1D_GET_WORLDCANVAS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
graph1d_get_worldcanvas \- Get the world canvas for a viewable graph.
.SH SYNOPSIS
.B #include <karma_graph1d.h>
.sp
.B KWorldCanvas graph1d_get_worldcanvas
.sp
(KViewableGraph vgraph)
.SH DESCRIPTION
Get the world canvas for a viewable graph.
.IP \fIvgraph\fP 1i
The viewable graph.
.SH RETURN VALUE
The KWorldCanvas object.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
