.TH GRAPH1D_REFRESH_IF_NEEDED 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
graph1d_refresh_if_needed \- Refresh a canvas if needed.
.SH SYNOPSIS
.B #include <karma_graph1d.h>
.sp
.B void graph1d_refresh_if_needed
.sp
(KWorldCanvas canvas)
.SH DESCRIPTION
Refresh a canvas if needed.
.IP \fIcanvas\fP 1i
The world canvas to be refreshed.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
