.TH GRAPH1D_GET_LAST 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
graph1d_get_last \- Get last viewable graph for a world canvas.
.SH SYNOPSIS
.B #include <karma_graph1d.h>
.sp
.B KViewableGraph graph1d_get_last
.sp
(KWorldCanvas canvas)
.SH DESCRIPTION
Get last viewable graph for a world canvas.
.IP \fIcanvas\fP 1i
The world canvas.
.SH RETURN VALUE
The viewable graph if there is one, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
