.TH GRAPH1D_GET_SIZE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
graph1d_get_size \- Get the size of a viewable graph.
.SH SYNOPSIS
.B #include <karma_graph1d.h>
.sp
.B unsigned int graph1d_get_size
.sp
(KViewableGraph vgraph, double **x, double **y)
.SH DESCRIPTION
Get the size of a viewable graph.
.IP \fIvgraph\fP 1i
The viewable graph.
.IP \fInum_points\fP 1i
The number of points in the graph is written here.
.IP \fIx\fP 1i
The pointer to the array of horizontal values is written here. This may
be NULL.
.IP \fIy\fP 1i
The pointer to the array of vertical values is written here. This may
be NULL.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
