.TH GRAPH1D_SAVE_ASCII 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
graph1d_save_ascii \- Save the data in a viewable graph in ASCII format.
.SH SYNOPSIS
.B #include <karma_graph1d.h>
.sp
.B flag graph1d_save_ascii
.sp
(KViewableGraph vgraph, Channel channel)
.SH DESCRIPTION
Save the data in a viewable graph in ASCII format.
.IP \fIvgraph\fP 1i
The viewable graph.
.IP \fIchannel\fP 1i
The Channel object to write to.
.SH RETURN VALUE
TRUE on success, else FALSE indicating error.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
