.TH GRAPH1D_TEST_IF_ZOOMED_HORIZONTALLY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
graph1d_test_if_zoomed_horizontally \- Test if a canvas is zoomed horizontally.
.SH SYNOPSIS
.B #include <karma_graph1d.h>
.sp
.B flag graph1d_test_if_zoomed_horizontally
.sp
(KWorldCanvas canvas)
.SH DESCRIPTION
Test if a canvas is zoomed horizontally.
.IP \fIcanvas\fP 1i
The world canvas.
.SH RETURN VALUE
TRUE if the canvas is zoomed, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
