.TH HI 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
hi \- Routines to save and restore history information
.SH PURPOSE
These routines are meant to provide which a mechanism for saving and
restoring history (parameter) information.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIhi_read\fP 1i
Read history information for a module.
.IP \fIhi_write\fP 1i
Write history information for a module.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
