.TH IARRAY_SET_DATA_RANGE 3 "14 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
iarray_set_data_range \- Set the range of data in an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_set_data_range
.sp
(iarray array, double minimum, double maximum)
.SH DESCRIPTION
This routine will set the range of data in an Intelligent
Array. The range information will be attached to the header.
.IP \fIarray\fP 1i
The array.
.IP \fIminimum\fP 1i
The minimum value. The name of the minimum value is constructed
by appending "__MINIMUM" to the array value name (see
<-iarray_value_name->).
If appropriate, the FITS-style "DATAMIN" keyword is written instead.
.IP \fImaximum\fP 1i
The maximum value. The name of the maximum value is constructed
by appending "__MAXIMUM" to the array value name
(see <-iarray_value_name->).
If appropriate, the FITS-style "DATAMAX" keyword is written instead.
.SH RETURN VALUE
TRUE if the range information is different from what was
already attached to the array, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
