.TH IARRAY_FILL_DOUBLE 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_fill_double \- Fill an Intelligent Array with a double precision float value.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_fill_double
.sp
(iarray array, double value)
.SH DESCRIPTION
Fill an Intelligent Array with a double precision float value.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIvalue\fP 1i
The fill value.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH NOTE
If filling a complex array, both the real and imaginary components
are filled with the fill value.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
