.TH IARRAY_REGRID_3D 3 "14 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
iarray_regrid_3D \- Regrid an array by iterating over the output array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_regrid_3D
.sp
(iarray out_arr, KwcsAstro out_ap,
iarray in_arr, KwcsAstro in_ap,
unsigned int sample_option, float *min, float *max,
flag verbose)
.SH DESCRIPTION
Regrid an array by iterating over the output array.
.IP \fIout_arr\fP 1i
The output array. The new grid must already be defined.
.IP \fIout_ap\fP 1i
The output KwcsAstro object.
.IP \fIin_arr\fP 1i
The input array.
.IP \fIin_ap\fP 1i
The input KwcsAstro object.
.IP \fIsample_option\fP 1i
The sample option to use.
.IP \fImin\fP 1i
The minimum value is written here. This is updated. This may be NULL.
.IP \fImax\fP 1i
The maximum value is written here. This is updated. This may be NULL.
.IP \fIverbose\fP 1i
If TRUE, diagnostic messages are displayed.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
