.TH IARRAY_SET_DIM_NAME 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_set_dim_name \- Change the name of a dimension of an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B void iarray_set_dim_name
.sp
(iarray array, unsigned int index, CONST char *name,
flag new_alloc)
.SH DESCRIPTION
Change the name of a dimension of an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIindex\fP 1i
The index of the dimension.
.IP \fIname\fP 1i
The new dimension name.
.IP \fInew_alloc\fP 1i
If TRUE, the routine will allocate a new copy of the dimension
name, else it will copy the pointer (in which case the name must never be
externally deallocated or changed).
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
