.TH IARRAY_FILL 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_fill \- Fill an Intelligent Array with a single value.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_fill
.sp
(iarray array, double value[2])
.SH DESCRIPTION
Fill an Intelligent Array with a single value.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIvalue\fP 1i
The fill value.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
