.TH IARRAY_SUM 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_sum \- Determine the sum of an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_sum
.sp
(iarray array, double sum[2])
.SH DESCRIPTION
Determine the sum of an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIsum\fP 1i
The routine will write the sum here.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
