.TH IARRAY_ARRAY_DESC 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_array_desc \- Get the array_desc for an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B multi_array * iarray_array_desc
.sp
(array)
.SH DESCRIPTION
Get the array_desc for an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.SH RETURN VALUE
The array_desc.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
