.TH IARRAY_DIM_NAME 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_dim_name \- Get dimension name in an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B CONST char * iarray_dim_name
.sp
(iarray array, unsigned int index)
.SH DESCRIPTION
This routine will get the name of a specified dimension in a
simple, n-dimensional array.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIindex\fP 1i
The index of the dimension.
.SH RETURN VALUE
A pointer to the name of the specified dimension.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
