.TH IARRAY_APPEND_HISTORY_STRING 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_append_history_string \- Add a history string to an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_append_history_string
.sp
(iarray array, CONST char *string,
flag new_alloc)
.SH DESCRIPTION
Add a history string to an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIstring\fP 1i
The history string to add.
.IP \fInew_alloc\fP 1i
If TRUE, the routine will allocate a new copy of the history
string, else it will copy the pointer (in which case the string must never
be externally deallocated or changed).
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
