.TH IARRAY_GET_FITS_AXIS 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_get_fits_axis \- Get the FITS axis number of a dimension.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B unsigned int iarray_get_fits_axis
.sp
(iarray array, unsigned int index)
.SH DESCRIPTION
Get the FITS axis number of a dimension.
.IP \fIarray\fP 1i
The Intelligent Array.
.IP \fIindex\fP 1i
The index of the dimension.
.SH RETURN VALUE
The FITS axis number on success, else 0.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
