.TH IARRAY_VALUE_NAME 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_value_name \- Get name of data in an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B CONST char * iarray_value_name
.sp
(iarray array)
.SH DESCRIPTION
Get name of data in an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.SH RETURN VALUE
The name of the data in the array.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
