.TH IARRAY_ARRAYP 3 "14 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
iarray_arrayp \- Get the array_pointer for an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B array_pointer * iarray_arrayp
.sp
(array)
.SH DESCRIPTION
Get the array_pointer for an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.SH RETURN VALUE
A pointer to the array_pointer. This pointer is invalidated by
any operation that causes the top level packet data to be reallocated.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
