.TH IARRAY_MULTI_INDEX 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_multi_index \- Get the index of the Intelligent Array within the multi_array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B unsigned int iarray_multi_index
.sp
(array)
.SH DESCRIPTION
Get the index of the Intelligent Array within the multi_array.
.IP \fIarray\fP 1i
The Intelligent Array.
.SH RETURN VALUE
The index.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
