.TH IARRAY_CREATE_2D 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_create_2D \- Create a 2-dimensional Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B iarray iarray_create_2D
.sp
(unsigned long ylen, unsigned long xlen,
unsigned int type)
.SH DESCRIPTION
This routine will create a 2-dimensional "Intelligent Array",
using the Karma general data structure format as the underlying data format
.IP \fIylen\fP 1i
The length of the most significant dimension (ie. the dimension with
the greatest stride in memory.
.IP \fIxlen\fP 1i
The length of the least significant dimension.
.IP \fItype\fP 1i
The type of the data. See <-ds_KARMA_DATA_TYPES-> for a list of
defined data types.
.SH RETURN VALUE
A dynamically allocated intelligent array on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH NOTES
The names of the dimensions will be the defaults: "Axis 0" and
"Axis 1", respectively.
.sp
The name of the element will be the default name: "Intensity".
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
