.TH IARRAY_DEALLOC2 3 "14 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
iarray_dealloc2 \- Deallocate an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B void iarray_dealloc2
.sp
(iarray array)
.SH DESCRIPTION
This routine will deallocate an "Intelligent Array". If the
environment variable "IARRAY_ALLOC_DEBUG" is set to "TRUE" then the routine
will print deallocation debugging information.
.IP \fIarray\fP 1i
The Intelligent Array. If this is NULL, nothing is done.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
