.TH IARRAY_COMPARE_SIZES 3 "14 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
iarray_compare_sizes \- Compare if two Intelligent Arrays are the same size.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_compare_sizes
.sp
(iarray array1, iarray array2, flag message)
.SH DESCRIPTION
Compare if two Intelligent Arrays are the same size.
.IP \fIarray1\fP 1i
One of the Intelligent Arrays to compare.
.IP \fIarray2\fP 1i
The other Intelligent Array to compare.
.IP \fImessage\fP 1i
If TRUE, explanatory messages are displayed.
.SH RETURN VALUE
TRUE of the number of dimensions and dimension lengths are the
same, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
