.TH IARRAY_MULTI_ARRAY 3 "14 Aug 2006" "Karma Distribution"
.SH FUNCTION
iarray_multi_array \- Get the multi_array for an Intelligent Array.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B multi_array * iarray_multi_array
.sp
(array)
.SH DESCRIPTION
Get the multi_array for an Intelligent Array.
.IP \fIarray\fP 1i
The Intelligent Array.
.SH RETURN VALUE
The multi_array.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
