.TH IARRAY_MATRIX_MULTIPLY 3 "14 Aug 2006" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
iarray_matrix_multiply \- Perform a matrix multiply.
.SH SYNOPSIS
.B #include <karma_iarray.h>
.sp
.B flag iarray_matrix_multiply
.sp
(iarray out, iarray in1, iarray in2, flag thread)
.SH DESCRIPTION
Perform a matrix multiply.
.IP \fIout\fP 1i
The output array (matrix).
.IP \fIin1\fP 1i
The first input array.
.IP \fIin2\fP 1i
The second input array.
.IP \fIthread\fP 1i
If TRUE, the operation may be threaded, else it will not be.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH NOTE
Only double precision arrays are supported.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
