.TH IEDIT_MAKE_LIST_DEFAULT_SLAVE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
iedit_make_list_default_slave \- Prepare image edit list for slavery.
.SH SYNOPSIS
.B #include <karma_iedit.h>
.sp
.B void iedit_make_list_default_slave
.sp
(KImageEditList ilist)
.SH DESCRIPTION
This routine will make a managed image edit instruction list the
default list for making slave list connections.
.IP \fIilist\fP 1i
The managed list.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
