.TH IEDIT_GET_INSTRUCTION_DESC 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
iedit_get_instruction_desc \- Get the list descriptor for image edit instructions.
.SH SYNOPSIS
.B #include <karma_iedit.h>
.sp
.B packet_desc * iedit_get_instruction_desc
.sp
()
.SH DESCRIPTION
Get the list descriptor for image edit instructions.
.SH RETURN VALUE
A pointer to the descriptor.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
