.TH IM 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
im \- Routines to do low level initialisation of modules
.SH PURPOSE
These routines are meant to provide low level initialisation for a module.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIim_register_module_name\fP 1i
Register a new name for the module.
.IP \fIim_register_module_version_date\fP 1i
Register a new version date for the module.
.IP \fIim_register_lib_version\fP 1i
Register the library version a module was compiled with.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
