.TH IM_REGISTER_MODULE_NAME 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
im_register_module_name \- Register a new name for the module.
.SH SYNOPSIS
.B #include <karma_im.h>
.sp
.B void im_register_module_name
.sp
(char *name_string)
.SH DESCRIPTION
Register a new name for the module.
.IP \fIname_string\fP 1i
The name string.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
