.TH IMC 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
imc \- Routines to convert between image formats
.SH PURPOSE
These routines provide a number of image conversion routines.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIimc_24to8\fP 1i
Convert a 24 bit truecolour image to an 8 bit pseudocolour image.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
