.TH J_DESTROY 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
j_destroy \- Destroy an associative array.
.SH SYNOPSIS
.B #include <karma_j.h>
.sp
.B void j_destroy
.sp
(KJoinedPairList list)
.SH DESCRIPTION
Destroy an associative array.
.IP \fIlist\fP 1i
The associative array.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
