.TH J_DESTROY_PAIR 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
j_destroy_pair \- Remove a key-value pair from an associative array.
.SH SYNOPSIS
.B #include <karma_j.h>
.sp
.B void j_destroy_pair
.sp
(KJoinedPair pair)
.SH DESCRIPTION
This routine will remove a key-value pair from an associative
array and will destroy all storage allocated for the pair.
.IP \fIpair\fP 1i
The key-value pair.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
