.TH J_GET_INFO 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
j_get_info \- Get information attached to associative array.
.SH SYNOPSIS
.B #include <karma_j.h>
.sp
.B void * j_get_info
.sp
(KJoinedPairList list)
.SH DESCRIPTION
This routine will get the arbitrary information pointer stored
with an associative array.
.IP \fIlist\fP 1i
The associative array.
.SH RETURN VALUE
The arbitrary information pointer.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
