.TH J_PROTO_VALUE_COPY_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
j_PROTO_value_copy_func \- This routine will copy a value.
.SH SYNOPSIS
.B #include <karma_j.h>
.sp
.B void * j_PROTO_value_copy_func
.sp
(void *value, uaddr length, flag *ok)
.SH DESCRIPTION
This routine will copy a value.
.IP \fIvalue\fP 1i
The value to copy.
.IP \fIlength\fP 1i
The length of the value in bytes.
.IP \fIok\fP 1i
The value TRUE will be written here on success, else FALSE is
written here.
.SH RETURN VALUE
A copy of the value on success.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
