.TH J_PROTO_KEY_DESTROY_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
j_PROTO_key_destroy_func \- This routine will destroy keys.
.SH SYNOPSIS
.B #include <karma_j.h>
.sp
.B void j_PROTO_key_destroy_func
.sp
(void *key)
.SH DESCRIPTION
This routine will destroy keys.
.IP \fIkey\fP 1i
The key to destroy.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
