.TH KCMAP_INITIALISE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
kcmap_initialise \- This routine will initialise the package.
.SH SYNOPSIS
.B #include <karma_kcmap.h>
.sp
.B void kcmap_initialise
.sp
()
.SH DESCRIPTION
This routine will initialise the package.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
