.TH KCMAP_DESTROY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
kcmap_destroy \- Destroy a colourmap.
.SH SYNOPSIS
.B #include <karma_kcmap.h>
.sp
.B void kcmap_destroy
.sp
(Kcolourmap cmap)
.SH DESCRIPTION
Destroy a colourmap.
.IP \fIcmap\fP 1i
The colourmap.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
