.TH KCMAP_PROTO_ALLOC_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
kcmap_PROTO_alloc_func \- Allocate colourcells.
.SH SYNOPSIS
.B #include <karma_kcmap.h>
.sp
.B unsigned int kcmap_PROTO_alloc_func
.sp
(unsigned int num_cells,
unsigned long *pixel_values,
unsigned int min_cells,
Kdisplay dpy_handle)
.SH DESCRIPTION
This routine will allocate a number of colourcells in a low
level colourmap (e.g. using the Xlib routine XAllocColorCells).
.IP \fInum_cells\fP 1i
The number of colourcells to allocate.
.IP \fIpixel_values\fP 1i
The array ofpixel values allocated will be written here.
.IP \fImin_cells\fP 1i
The minimum number of colourcells to allocate. The routine
will try to allocate at least this number of colourcells.
.IP \fIdpy_handle\fP 1i
The low level display handle. The meaning of this value
depends on the lower level graphics library used.
.SH RETURN VALUE
The number of colourcells allocated.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
