.TH KCMAP_REGISTER_ATT_NOTIFY_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
kcmap_register_att_notify_func \- Register an attribute change function.
.SH SYNOPSIS
.B #include <karma_kcmap.h>
.sp
.B KCallbackFunc kcmap_register_att_notify_func
.sp
(Kcolourmap cmap,
void (*func) (), void *info)
.SH DESCRIPTION
This routine will register an attribute notify function for a
high level colourmap. The attribute notify function will be called whenever
the colourmap attributes are changed (see <-kcmap_set_attributes->).
Many attribute notify functions may be registered per colourmap. The first
function registered is the first function called upon attribute changes.
.IP \fIcmap\fP 1i
The colourmap.
.IP \fIfunc\fP 1i
The function which is called when the attributes are changed.
The prototype function is <-kcmap_PROTO_att_notify_func->.
.IP \fIinfo\fP 1i
The initial arbitrary colourmap information pointer.
.SH RETURN VALUE
A KCallbackFunc object.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
