.TH KWIN_GET_ASSOCIATED_OBJECT 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
kwin_get_associated_object \- Get an associated object for a pixel canvas.
.SH SYNOPSIS
.B #include <karma_kwin.h>
.sp
.B void * kwin_get_associated_object
.sp
(KPixCanvas canvas, CONST void *key)
.SH DESCRIPTION
Get an associated object for a pixel canvas.
.IP \fIcanvas\fP 1i
The pixel canvas.
.IP \fIkey\fP 1i
The key to search for.
.SH RETURN VALUE
A pointer to the associated object. NULL is returned if the key
is not found.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
