.TH KWIN_REFRESH_IF_VISIBLE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
kwin_refresh_if_visible \- Refresh a pixel canvas if it is visible.
.SH SYNOPSIS
.B #include <karma_kwin.h>
.sp
.B flag kwin_refresh_if_visible
.sp
(KPixCanvas canvas, flag clear)
.SH DESCRIPTION
Refresh a pixel canvas if it is visible.
.IP \fIcanvas\fP 1i
The pixel canvas.
.IP \fIclear\fP 1i
If TRUE the canvas is cleared prior to refreshing.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
