.TH KWIN_FREE_CACHE_DATA 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
kwin_free_cache_data \- Free some cache data allocated by <-kwin_draw_pc_image->.
.SH SYNOPSIS
.B #include <karma_kwin.h>
.sp
.B void kwin_free_cache_data
.sp
(KPixCanvasImageCache cache)
.SH DESCRIPTION
Free some cache data allocated by <-kwin_draw_pc_image->.
.IP \fIcache\fP 1i
The cache data.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
