.TH KWIN_SET_ATTRIBUTES 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
kwin_set_attributes \- Set the attributes for a pixel canvas.
.SH SYNOPSIS
.B #include <karma_kwin.h>
.sp
.B void kwin_set_attributes
.sp
(KPixCanvas canvas, ...)
.SH DESCRIPTION
Set the attributes for a pixel canvas.
.IP \fIcanvas\fP 1i
The pixel canvas.
.IP \fI...\fP 1i
The optional list of parameter attribute-key attribute-value
pairs must follow. This list must be terminated with the value
KWIN_ATT_END. See <-kwin_ATTRIBUTES-> for the list of attributes.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
