.TH KWIN_GET_STRING_SIZE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
kwin_get_string_size \- Determine the size of a string.
.SH SYNOPSIS
.B #include <karma_kwin.h>
.sp
.B flag kwin_get_string_size
.sp
(KPixCanvasFont font, CONST char *string, ...)
.SH DESCRIPTION
Determine the size of a string.
.IP \fIfont\fP 1i
The font.
.IP \fIstring\fP 1i
The string.
.IP \fI...\fP 1i
The optional list of parameter attribute-key attribute-value-ptr
pairs must follow. This list must be terminated with the value
KWIN_STRING_END. See <-kwin_STRING_ATTRIBUTES-> for the list of attributes.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
