.TH KWIN_FILL_ELLIPSE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
kwin_fill_ellipse \- Draw a filled ellipse onto a pixel canvas.
.SH SYNOPSIS
.B #include <karma_kwin.h>
.sp
.B flag kwin_fill_ellipse
.sp
(KPixCanvas canvas,
double cx, double cy, double rx, double ry,
unsigned long pixel_value)
.SH DESCRIPTION
Draw a filled ellipse onto a pixel canvas.
.IP \fIcanvas\fP 1i
The canvas.
.IP \fIcx\fP 1i
The horizontal co-ordinate of the centre of the ellipse.
.IP \fIcy\fP 1i
The vertical co-ordinate of the centre of the ellipse.
.IP \fIrx\fP 1i
The horizontal radius.
.IP \fIry\fP 1i
The vertical radius.
.IP \fIpixel_value\fP 1i
The pixel value to use.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
