.TH LISTW_PROTO_POSITION_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
listw_PROTO_position_func \- Position event callback.
.SH SYNOPSIS
.B #include <karma_listw.h>
.sp
.B flag listw_PROTO_position_func
.sp
(KListWidget list, unsigned int index,
unsigned int event_code, void *e_info,
void **f_info)
.SH DESCRIPTION
This routine is a position event consumer for a list widget.
.IP \fIlist\fP 1i
The list widget on which the event occurred.
.IP \fIindex\fP 1i
The index in list of strings for which the event occurred.
.IP \fIevent_code\fP 1i
The arbitrary event code.
.IP \fIe_info\fP 1i
A pointer to arbitrary event information.
.IP \fIf_info\fP 1i
A pointer to an arbitrary function information pointer.
.SH RETURN VALUE
TRUE if the event was consumed, else FALSE indicating that
the event is still to be processed.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
