.TH LISTW_CREATE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
listw_create \- Create a list widget.
.SH SYNOPSIS
.B #include <karma_listw.h>
.sp
.B KListWidget listw_create
.sp
()
.SH DESCRIPTION
Create a list widget.
.SH RETURN VALUE
A list widget object on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
