.TH M_GET_TOTAL_ALLOCATED 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
m_get_total_allocated \- Get total number of bytes currently allocated.
.SH SYNOPSIS
.B #include <karma_m.h>
.sp
.B uaddr m_get_total_allocated
.sp
()
.SH DESCRIPTION
Get total number of bytes currently allocated.
.SH RETURN VALUE
The number of bytes allocated.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
