.TH M_MAP_TEST 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
m_map_test \- Test if memory mapping is supported.
.SH SYNOPSIS
.B #include <karma_m.h>
.sp
.B flag m_map_test
.sp
()
.SH DESCRIPTION
Test if memory mapping is supported.
.SH RETURN VALUE
TRUE if supported, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
