.TH M_SHM_TEST_IF_AVAILABLE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
m_shm_test_if_available \- Test if shared memory available.
.SH SYNOPSIS
.B #include <karma_m.h>
.sp
.B flag m_shm_test_if_available
.sp
()
.SH DESCRIPTION
Test if shared memory available.
.SH RETURN VALUE
TRUE if shared memory is available, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
