.TH M_SHM_DELETE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
m_shm_delete \- Delete a shared memory segment.
.SH SYNOPSIS
.B #include <karma_m.h>
.sp
.B void m_shm_delete
.sp
(int shmid)
.SH DESCRIPTION
Delete a shared memory segment.
.IP \fIshmid\fP 1i
The ID of the shared memory segment to mark for deletion.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
