.TH M_UNMAP 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
m_unmap \- Unmap a region of memory.
.SH SYNOPSIS
.B #include <karma_m.h>
.sp
.B flag m_unmap
.sp
(void *addr, uaddr size)
.SH DESCRIPTION
Unmap a region of memory.
.IP \fIaddr\fP 1i
The start address of the region.
.IP \fIsize\fP 1i
The size of the region.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
