.TH MD_MD5_TRANSFORM 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
md_md5_transform \- Run the core MD5 transform over a block of data.
.SH SYNOPSIS
.B #include <karma_md.h>
.sp
.B void md_md5_transform
.sp
(unsigned char buf[16], CONST unsigned char in[64])
.SH DESCRIPTION
Run the core MD5 transform over a block of data.
.IP \fIbuf\fP 1i
The digest accumulation buffer.
.IP \fIin\fP 1i
The block of data.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
