.TH MD_MD5_INIT 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
md_md5_init \- Initialise MD5 context.
.SH SYNOPSIS
.B #include <karma_md.h>
.sp
.B MD5Context md_md5_init
.sp
()
.SH DESCRIPTION
Initialise MD5 context.
.SH RETURN VALUE
An MD5 context.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
