.TH MODULE 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
module \- Routines to initialise and sequence modules
.SH PURPOSE
These routines are meant to provide high level routines to perform
initialisation and execution of generic modules.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fImodule_run\fP 1i
Initialise and then run a generic module.
.IP \fImodule_process_argvs\fP 1i
Process a shell command line.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
