.TH MT_DISABLE_NOTIFY_PIPE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
mt_disable_notify_pipe \- Disable the notification pipe.
.SH SYNOPSIS
.B #include <karma_mt.h>
.sp
.B void mt_disable_notify_pipe
.sp
(KThreadPool pool)
.SH DESCRIPTION
Disable the notification pipe.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Safe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
