.TH MT_WAIT_FOR_ALL_JOBS 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
mt_wait_for_all_jobs \- Wait for all previously launched jobs to complete.
.SH SYNOPSIS
.B #include <karma_mt.h>
.sp
.B void mt_wait_for_all_jobs
.sp
(KThreadPool pool)
.SH DESCRIPTION
Wait for all previously launched jobs to complete.
.IP \fIpool\fP 1i
The thread pool.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Safe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
