.TH N_GAUSSIAN 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
n_gaussian \- Compute a random number with Gaussian distribution.
.SH SYNOPSIS
.B #include <karma_n.h>
.sp
.B double n_gaussian
.sp
()
.SH DESCRIPTION
This routine will compute a random number with a Gaussian
distribution. The mean is 0.0 and the variance is 1.0
.SH RETURN VALUE
The number.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
