.TH OVERLAY_DESTROY_VIEWABLE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
overlay_destroy_viewable \- Destroy a viewable overlay list.
.SH SYNOPSIS
.B #include <karma_overlay.h>
.sp
.B void overlay_destroy_viewable
.sp
(KViewableOverlayList vlist)
.SH DESCRIPTION
Destroy a viewable overlay list.
.IP \fIvlist\fP 1i
The KViewableOverlayList object to destroy.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
