.TH OVERLAY_SET_CANVAS_ATTRIBUTES 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
overlay_set_canvas_attributes \- Set the canvas attributes for overlay list display.
.SH SYNOPSIS
.B #include <karma_overlay.h>
.sp
.B void overlay_set_canvas_attributes
.sp
(KWorldCanvas canvas, ...)
.SH DESCRIPTION
Set the canvas attributes for overlay list display.
.IP \fIcanvas\fP 1i
The world canvas object.
.IP \fI...\fP 1i
The optional list of parameter attribute-key attribute-value
pairs must follow. This list must be terminated with the value
OVERLAY_CANVAS_ATT_END. See <-overlay_CANVAS_ATTRIBUTES-> for a list of
defined attributes.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
