.TH OVERLAY_VECTOR 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
overlay_vector \- Add a vector to an overlay list.
.SH SYNOPSIS
.B #include <karma_overlay.h>
.sp
.B unsigned int overlay_vector
.sp
(KOverlayList olist,
unsigned int stype, double sx, double sy,
unsigned int dtype, double dx, double dy,
CONST char *colourname)
.SH DESCRIPTION
This routine will add a vector (directed line) to an overlay
object list. See also <-overlay_vectors->.
.IP \fIolist\fP 1i
The overlay list object.
.IP \fIstype\fP 1i
The type of the start co-ordinate. See <-overlay_COORDINATE_TYPES->
for a list of supported co-ordinate types.
.IP \fIsx\fP 1i
The horizontal position of the start co-ordinate.
.IP \fIsy\fP 1i
The vertical position of the start co-ordinate.
.IP \fIdtype\fP 1i
The type of the vector direction. See <-overlay_COORDINATE_TYPES->
for a list of supported co-ordinate types.
.IP \fIdx\fP 1i
The horizontal vector direction.
.IP \fIdy\fP 1i
The vertical vector direction.
.IP \fIcolourname\fP 1i
The colour name.
.SH RETURN VALUE
The objectID on success, else 0.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
