.TH OVERLAY_HAVE_TOKEN 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
overlay_have_token \- Test if an overay list has the token.
.SH SYNOPSIS
.B #include <karma_overlay.h>
.sp
.B flag overlay_have_token
.sp
(KOverlayList olist)
.SH DESCRIPTION
Test if an overay list has the token.
.IP \fIolist\fP 1i
The overlay list object.
.SH RETURN VALUE
TRUE if the overlay list has the token, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
