.TH PANEL_PUSH_ONTO_STACK 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
panel_push_onto_stack \- Push a control panel object onto the control panel stack.
.SH SYNOPSIS
.B #include <karma_panel.h>
.sp
.B void panel_push_onto_stack
.sp
(KControlPanel panel)
.SH DESCRIPTION
Push a control panel object onto the control panel stack.
.IP \fIpanel\fP 1i
The control panel.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
