.TH PANEL_PROTO_CHANGE_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
panel_PROTO_change_func \- Item change callback.
.SH SYNOPSIS
.B #include <karma_panel.h>
.sp
.B void panel_PROTO_change_func
.sp
(KPanelItem item, void **info)
.SH DESCRIPTION
This function is called whenever an items value is changed.
.IP \fIitem\fP 1i
The panel item which changed.
.IP \fIinfo\fP 1i
The pointer to the arbitrary information pointer.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
