.TH PGP 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
pgp \- Routines to interface with PGP
.SH PURPOSE
These routines are meant to provide a simple interface to PGP.
.SH LIBRARY
karma
.SH LINK WITH
-lkarma
.SH FUNCTIONS
.IP \fIpgp_decrypt\fP 1i
Decrypt a block of data using PGP and PGPdaemon.
.IP \fIpgp_encrypt\fP 1i
Encrypt a block of data using PGP.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
