.TH PIO_READ_STRING 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
pio_read_string \- Read a string from a channel object.
.SH SYNOPSIS
.B #include <karma_pio.h>
.sp
.B char * pio_read_string
.sp
(Channel channel, unsigned int *length)
.SH DESCRIPTION
Read a string from a channel object.
.IP \fIchannel\fP 1i
The channel object.
.IP \fIlength\fP 1i
The length of the string will be written here. If this is NULL,
nothing is written here.
.SH RETURN VALUE
A pointer to a dynamically allocated string on success,
else NULL. If a zero length string was read, the returned buffer is one
character long and contains the '\0' character.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
