.TH PIO_READ_FLOAT_NANTRAP 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
pio_read_float_nantrap \- Read floating point data from a channel object, trapping NaNs.
.SH SYNOPSIS
.B #include <karma_pio.h>
.sp
.B flag pio_read_float_nantrap
.sp
(Channel channel, float *data, flag *was_nan)
.SH DESCRIPTION
This routine will read a floating point number from a channel
object and will trap IEEE Not-A-Number (NaN) values.
.IP \fIchannel\fP 1i
The channel object.
.IP \fIdata\fP 1i
The data will be written here. This will be written in host natural
format. The data will be converted from IEEE network format prior to
writing.
.IP \fIwas_nan\fP 1i
The value TRUE will be written here if the value was NaN, else
FALSE is written here. If this is NULL then NaN values are not trapped.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
