.TH PSW_SET_ATTRIBUTES 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
psw_set_attributes \- Set the attributes for a PostScriptPage object.
.SH SYNOPSIS
.B #include <karma_psw.h>
.sp
.B flag psw_set_attributes
.sp
(PostScriptPage pspage, ...)
.SH DESCRIPTION
Set the attributes for a PostScriptPage object.
.IP \fIpspage\fP 1i
The PostScriptPage object.
.IP \fI...\fP 1i
The optional list of parameter attribute-key attribute-value
pairs must follow. This list must be terminated with the value
PSW_ATT_END. See <-psw_ATTRIBUTES-> for the list of attributes.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
