.TH PSW_RGB_LINE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
psw_rgb_line \- Write a colour line to a PostScriptPage object.
.SH SYNOPSIS
.B #include <karma_psw.h>
.sp
.B flag psw_rgb_line
.sp
(PostScriptPage pspage, double red, double green,double blue,
double xstart, double ystart, double xend, double yend)
.SH DESCRIPTION
Write a colour line to a PostScriptPage object.
.IP \fIpspage\fP 1i
The PostScriptPage object.
.IP \fIred\fP 1i
The red component value. The range is: 0.0 (dark) to 1.0 (light)
.IP \fIgreen\fP 1i
The green component value. The range is: 0.0 (dark) to 1.0 (light)
.IP \fIblue\fP 1i
The blue component value. The range is: 0.0 (dark) to 1.0 (light)
.IP \fIxstart\fP 1i
The x starting point (scaled from 0.0 to 1.0).
.IP \fIystart\fP 1i
The y starting point (scaled from 0.0 to 1.0).
.IP \fIxend\fP 1i
The x ending point (scaled from 0.0 to 1.0).
.IP \fIyend\fP 1i
The y ending point (scaled from 0.0 to 1.0).
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
