.TH R_CLOSE_CONNECTION 3 "24 Dec 2005" "Karma Distribution"
.SH FUNCTION
r_close_connection \- Close a connection.
.SH SYNOPSIS
.B #include <karma_r.h>
.sp
.B flag r_close_connection
.sp
(int connection)
.SH DESCRIPTION
Close a connection.
.IP \fIconnection\fP 1i
The connection to close.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
