.TH R_GET_KARMABASE 3 "24 Dec 2005" "Karma Distribution"
.SH FUNCTION
r_get_karmabase \- Get the pathname of the installed runtime Karma.
.SH SYNOPSIS
.B #include <karma_r.h>
.sp
.B CONST char * r_get_karmabase
.sp
()
.SH DESCRIPTION
Get the pathname of the installed runtime Karma.
.SH RETURN VALUE
The pathname on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
