.TH R_GETPPID 3 "24 Dec 2005" "Karma Distribution"
.SH FUNCTION
r_getppid \- Get the parent process ID.
.SH SYNOPSIS
.B #include <karma_r.h>
.sp
.B int r_getppid
.sp
()
.SH DESCRIPTION
Get the parent process ID.
.SH RETURN VALUE
The parent process ID.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
