.TH R_SEND_FD 3 "24 Dec 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
r_send_fd \- Send a file descriptor over a connection.
.SH SYNOPSIS
.B #include <karma_r.h>
.sp
.B flag r_send_fd
.sp
(int conn_fd, int send_fd)
.SH DESCRIPTION
Send a file descriptor over a connection.
.IP \fIconn_fd\fP 1i
The connection file descriptor.
.IP \fIsend_fd\fP 1i
The file descriptor to send.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
