.TH RP_DESTROY 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
rp_destroy \- Destroy a random pool of bytes, erasing all information.
.SH SYNOPSIS
.B #include <karma_rp.h>
.sp
.B void rp_destroy
.sp
(RandPool rp)
.SH DESCRIPTION
Destroy a random pool of bytes, erasing all information.
.IP \fIrp\fP 1i
The random pool.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
