.TH S_INSTALL_HANDLERS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
s_install_handlers \- Install recommended signal handlers for SIGINT and SIGTERM.
.SH SYNOPSIS
.B #include <karma_s.h>
.sp
.B flag s_install_handlers
.sp
()
.SH DESCRIPTION
Install recommended signal handlers for SIGINT and SIGTERM.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
