.TH S_UNBLOCK 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
s_unblock \- Unblock a signal.
.SH SYNOPSIS
.B #include <karma_s.h>
.sp
.B void s_unblock
.sp
(int signal)
.SH DESCRIPTION
This routine will cause a signal to be unblocked. If the signal
is not already blocked, no action is taken.
.IP \fIsignal\fP 1i
The signal to unblock.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH NOTE
The signal will only be unblocked if previously blocked by a call
to <-s_block->.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
