.TH SCATPLT_SET_ACTIVE 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
scatplt_set_active \- Set active state for a scatter plot controlled refresh.
.SH SYNOPSIS
.B #include <karma_scatplt.h>
.sp
.B flag scatplt_set_active
.sp
(KScatterPlot plot, flag active, flag force_refresh,
flag refresh_if_changed, flag exclusive, uaddr key)
.SH DESCRIPTION
This routine will make a scatter plot active or inactive.
.IP \fIplot\fP 1i
The scatter plot.
.IP \fIactive\fP 1i
If TRUE, the scatter plot is made active, else it is made
inactive.
.IP \fIforce_refresh\fP 1i
If TRUE, the canvas is always refreshed.
.IP \fIrefresh_if_changed\fP 1i
If TRUE, the canvas is refreshed if the scatter plot
active state changed.
.IP \fIexclusive\fP 1i
If TRUE and <<active>> is TRUE, make this scatter plot the only
active one for this canvas. Other scatter plots for this canvas will be
made inactive.
.IP \fIkey\fP 1i
The key to use for inactivation of other scatter plots. If this is 0
then all other scatter plots will be made inactive.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
