.TH SCATPLT_GET_WORLDCANVAS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
scatplt_get_worldcanvas \- Get the world canvas for a scatter plot.
.SH SYNOPSIS
.B #include <karma_scatplt.h>
.sp
.B KWorldCanvas scatplt_get_worldcanvas
.sp
(KScatterPlot plot)
.SH DESCRIPTION
Get the world canvas for a scatter plot.
.IP \fIplot\fP 1i
The scatter plot.
.SH RETURN VALUE
The KWorldCanvas object.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
