.TH SCATPLT_DESTROY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
scatplt_destroy \- Destroy scatter plot.
.SH SYNOPSIS
.B #include <karma_scatplt.h>
.sp
.B void scatplt_destroy
.sp
(KScatterPlot plot)
.SH DESCRIPTION
This routine will destroy a scatter plot.
.IP \fIplot\fP 1i
The scatter plot.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
