.TH ST_SPN 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
st_spn \- Find maximum leading segment in string with inclusion.
.SH SYNOPSIS
.B #include <karma_st.h>
.sp
.B int st_spn
.sp
(CONST char *string, CONST char *charset)
.SH DESCRIPTION
Find maximum leading segment in string with inclusion.
.IP \fIstring\fP 1i
The string.
.IP \fIcharset\fP 1i
The set of inclusion characters.
.SH RETURN VALUE
The number of characters in the leading segment.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
