.TH ST_TOL 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
st_tol \- Convert a string to a long integer.
.SH SYNOPSIS
.B #include <karma_st.h>
.sp
.B long st_tol
.sp
(CONST char *str, char **ptr, int base)
.SH DESCRIPTION
Convert a string to a long integer.
.IP \fIstr\fP 1i
The string.
.IP \fIptr\fP 1i
A pointer to the first invalid character is written here. If this is
NULL, nothing is written here.
.IP \fIbase\fP 1i
The base of the number system.
.SH RETURN VALUE
The integer value.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
