.TH ST_UPR 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
st_upr \- Convert a string to uppercase.
.SH SYNOPSIS
.B #include <karma_st.h>
.sp
.B char * st_upr
.sp
(char *string)
.SH DESCRIPTION
Convert a string to uppercase.
.IP \fIstring\fP 1i
The string.
.SH RETURN VALUE
The address of the string.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
