.TH T_CHECK_POWER_OF_2 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
t_check_power_of_2 \- Check if a number is a power of 2.
.SH SYNOPSIS
.B #include <karma_t.h>
.sp
.B flag t_check_power_of_2
.sp
(unsigned int number)
.SH DESCRIPTION
Check if a number is a power of 2.
.IP \fInumber\fP 1i
The number.
.SH RETURN VALUE
TRUE if the number is a power of 2, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
