.TH VC_GET_DPY_HANDLE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
vc_get_dpy_handle \- Generate a display handle for later use.
.SH SYNOPSIS
.B #include <karma_vc.h>
.sp
.B Kdisplay vc_get_dpy_handle
.sp
()
.SH DESCRIPTION
Generate a display handle for later use.
.SH RETURN VALUE
A pointer to the display handle on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
