.TH VIEWIMG_GET_WORLDCANVAS 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
viewimg_get_worldcanvas \- Get the world canvas for a viewable image.
.SH SYNOPSIS
.B #include <karma_viewimg.h>
.sp
.B KWorldCanvas viewimg_get_worldcanvas
.sp
(ViewableImage vimage)
.SH DESCRIPTION
Get the world canvas for a viewable image.
.IP \fIvimage\fP 1i
The ViewableImage object.
.SH RETURN VALUE
The KWorldCanvas object.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
