.TH VIEWIMG_TEST_ACTIVE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
viewimg_test_active \- Test if viewable image is active.
.SH SYNOPSIS
.B #include <karma_viewimg.h>
.sp
.B flag viewimg_test_active
.sp
(ViewableImage vimage)
.SH DESCRIPTION
This routine will test if a viewable image is the active image
for its associated world canvas.
.IP \fIvimage\fP 1i
The viewable image.
.SH RETURN VALUE
TRUE if the viewable image is actice, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
