.TH VIEWIMG_SET_CANVAS_ATTRIBUTES 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
viewimg_set_canvas_attributes \- Set the viewable image attributes for a world canvas.
.SH SYNOPSIS
.B #include <karma_viewimg.h>
.sp
.B void viewimg_set_canvas_attributes
.sp
(KWorldCanvas canvas, ...)
.SH DESCRIPTION
This routine will control the autoscaling options used when
viewable images are displayed on their associated world canvas.
.IP \fIcanvas\fP 1i
The world canvas.
.IP \fI...\fP 1i
The list of parameter attribute-key attribute-value pairs
must follow. This list must be terminated with the VIEWIMG_ATT_END.
See <-viewimg_CANVAS_ATTRIBUTES-> for the list of attributes.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH NOTE
The canvas is not refreshed by this operation.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
