.TH VIEWIMG_REGISTER_POSITION_EVENT_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
viewimg_register_position_event_func \- Register position event callback.
.SH SYNOPSIS
.B #include <karma_viewimg.h>
.sp
.B KCallbackFunc viewimg_register_position_event_func
.sp
(KWorldCanvas canvas,
flag (*func) (),
void *f_info)
.SH DESCRIPTION
This routine will register a position event function for a world
canvas which has a number of ViewableImage objects associated with it.
The position event function will be called whenever a position event on the
canvas has not been consumed. Many position event functions may be
registered per canvas. The first function registered is the first function
called upon a position event.
.IP \fIcanvas\fP 1i
The world canvas object.
.IP \fIfunc\fP 1i
The function that is called when a position event occurs. The
prototype function is <-viewimg_PROTO_position_func->.
.IP \fIf_info\fP 1i
The initial arbitrary function information pointer.
.SH RETURN VALUE
A handle to a KCallbackFunc object.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
