.TH VIEWIMG_PARTIAL_REFRESH 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
viewimg_partial_refresh \- Perform a partial refresh of a canvas.
.SH SYNOPSIS
.B #include <karma_viewimg.h>
.sp
.B flag viewimg_partial_refresh
.sp
(KWorldCanvas canvas, unsigned int num_areas,
KPixCanvasRefreshArea *areas)
.SH DESCRIPTION
This routine will perform a partial refresh of a canvas. This
call is similar to <<kwin_partial_refresh>> except that areas are not
cleared prior to drawing if they lie within the image boundary.
.IP \fIcanvas\fP 1i
The world canvas.
.IP \fInum_areas\fP 1i
The number of areas in the pixel canvas to refresh.
.IP \fIareas\fP 1i
The list of areas to refresh. The values here are updated to ensure
all points lie within the boundaries of the underlaying pixel canvas.
.SH RETURN VALUE
TRUE on success, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
