.TH VIEWIMG_SET_ARRAY_ATTRIBUTES 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
viewimg_set_array_attributes \- Set the attributes for an array of viewable images.
.SH SYNOPSIS
.B #include <karma_viewimg.h>
.sp
.B void viewimg_set_array_attributes
.sp
(ViewableImage *vimages, unsigned int len,
...)
.SH DESCRIPTION
Set the attributes for an array of viewable images.
.IP \fIvimages\fP 1i
The array of ViewableImage objects.
.IP \fIlen\fP 1i
The length of the array.
.IP \fI...\fP 1i
The list of parameter attribute-key attribute-value pairs
must follow. This list must be terminated with the VIEWIMG_VATT_END. See
<-viewimg_VIMAGE_ATTRIBUTES-> for the list of attributes.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
