.TH VRENDER_CREATE_CONTEXT 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
vrender_create_context \- Create a context for volume rendering.
.SH SYNOPSIS
.B #include <karma_vrender.h>
.sp
.B KVolumeRenderContext vrender_create_context
.sp
(void *info, ...)
.SH DESCRIPTION
Create a context for volume rendering.
.IP \fIinfo\fP 1i
An arbitrary information pointer associated with the context.
.IP \fI...\fP 1i
The optional list of parameter attribute-key attribute-value
pairs must follow. This list must be terminated with the value
VRENDER_CONTEXT_ATT_END. See <-vrender_ATTRIBUTES-> for a list of defined
attributes.
.SH RETURN VALUE
A KVolumeRenderContext on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
