.TH VRENDER_PROTO_RENDER_NOTIFY_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
vrender_PROTO_render_notify_func \- Volume rendering completed callback.
.SH SYNOPSIS
.B #include <karma_vrender.h>
.sp
.B void vrender_PROTO_render_notify_func
.sp
(void *info)
.SH DESCRIPTION
This routine registers the completion of a volume render
request.
.IP \fIinfo\fP 1i
The arbitrary information pointer.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
