.TH W_TEST_SUPPORTED 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
w_test_supported \- Test if application supports work functions.
.SH SYNOPSIS
.B #include <karma_w.h>
.sp
.B flag w_test_supported
.sp
()
.SH DESCRIPTION
This routine will determine if work functions have been supported
by the application.
.SH RETURN VALUE
TRUE if work functions are supported, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
