.TH W_WORK_TO_BE_DONE 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
w_work_to_be_done \- Test for pending work functions waiting to be called.
.SH SYNOPSIS
.B #include <karma_w.h>
.sp
.B flag w_work_to_be_done
.sp
()
.SH DESCRIPTION
This routine will determine if there are any pending work
functions waiting to be called.
.SH RETURN VALUE
TRUE if any work functions are pending, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH NOTE
Disabling support for work functions via <w_unregister_support> has
no effect on this function.
.sp
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
