.TH WCS_ASTRO_GET_EQUINOX 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
wcs_astro_get_equinox \- Get the Equinox.
.SH SYNOPSIS
.B #include <karma_wcs.h>
.sp
.B unsigned int wcs_astro_get_equinox
.sp
(KwcsAstro ap)
.SH DESCRIPTION
Get the Equinox.
.IP \fIap\fP 1i
The KwcsAstro object.
.SH RETURN VALUE
The year of the Equinox (typically 1950 or 2000).
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
