.TH WCS_ASTRO_HAS_CHROMATIC_ABERRATION 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
wcs_astro_has_chromatic_aberration \- Test if a co-ordinate system has chromatic aberration.
.SH SYNOPSIS
.B #include <karma_wcs.h>
.sp
.B flag wcs_astro_has_chromatic_aberration
.sp
(KwcsAstro ap)
.SH DESCRIPTION
Test if a co-ordinate system has chromatic aberration.
.IP \fIap\fP 1i
The KwcsAstro object.
.SH RETURN VALUE
TRUE if chromatic aberration is present, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
