.TH WCS_ASTRO_TEST_RADEC 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
wcs_astro_test_radec \- Test if a KwcsAstro object has RA/GLON and DEC/GLAT defined.
.SH SYNOPSIS
.B #include <karma_wcs.h>
.sp
.B flag wcs_astro_test_radec
.sp
(KwcsAstro ap)
.SH DESCRIPTION
Test if a KwcsAstro object has RA/GLON and DEC/GLAT defined.
.IP \fIap\fP 1i
The KwcsAstro object. This may be NULL.
.SH RETURN VALUE
TRUE if the KwcsAstro object has RA and DEC defined, else FALSE.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
