.TH WCS_ASTRO_SETUP 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
wcs_astro_setup \- Setup for Astronomical Sky Co-ordinate projections.
.SH SYNOPSIS
.B #include <karma_wcs.h>
.sp
.B KwcsAstro wcs_astro_setup
.sp
(CONST packet_desc *pack_desc, CONST char *packet)
.SH DESCRIPTION
Setup for Astronomical Sky Co-ordinate projections.
.IP \fIpack_desc\fP 1i
The packet descriptor containing the FITS-style keywords.
.IP \fIpacket\fP 1i
The packet data containing the FITS-stype keyword data.
.SH RETURN VALUE
A KwcsAstro object on success, else NULL.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
