.TH WCS_ASTRO_FORMAT_HMS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
wcs_astro_format_hms \- Format a time value into a string.
.SH SYNOPSIS
.B #include <karma_wcs.h>
.sp
.B void wcs_astro_format_hms
.sp
(char *string, double hours)
.SH DESCRIPTION
Format a time value into a string.
.IP \fIstring\fP 1i
The string to write to. Sufficient storage must be available.
.IP \fIhours\fP 1i
The time value in hours.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
