.TH WCS_ASTRO_DESTROY 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
wcs_astro_destroy \- Destroy KwcsAstro object.
.SH SYNOPSIS
.B #include <karma_wcs.h>
.sp
.B void wcs_astro_destroy
.sp
(KwcsAstro ap)
.SH DESCRIPTION
Destroy KwcsAstro object.
.IP \fIap\fP 1i
The KwcsAstro object.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
