.TH XC_GET_CMAP 3 "13 Nov 2005" "Karma Distribution"
.SH FUNCTION
xc_get_cmap \- Get the X11 colourmap for a display handle.
.SH SYNOPSIS
.B #include <karma_xc.h>
.sp
.B Colormap xc_get_cmap
.sp
(Kdisplay dpy_handle)
.SH DESCRIPTION
Get the X11 colourmap for a display handle.
.IP \fIdpy_handle\fP 1i
The display handle.
.SH RETURN VALUE
The X11 colourmap.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
