.TH XTMISC_INIT_POST_REALISE_ARG_PROCESS 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
xtmisc_init_post_realise_arg_process \- Process and remove arguments after main widget realisation.
.SH SYNOPSIS
.B #include <karma_xtmisc.h>
.sp
.B void xtmisc_init_post_realise_arg_process
.sp
(int *argc_in_out,
String *argv_in_out)
.SH DESCRIPTION
Process and remove arguments after main widget realisation.
.IP \fIargc_in_out\fP 1i
As for <<XtVaAppInitialize>>.
.IP \fIargv_in_out\fP 1i
As for <<XtVaAppInitialize>>.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
