.TH XTMISC_EVENT_INIT 3 "13 Nov 2005" "Karma Distribution"
.SH EXPERIMENTAL_FUNC
xtmisc_event_init \- Initialise periodic event management support under Xt.
.SH SYNOPSIS
.B #include <karma_xtmisc.h>
.sp
.B void xtmisc_event_init
.sp
(XtAppContext app_context)
.SH DESCRIPTION
Initialise periodic event management support under Xt.
.IP \fIapp_context\fP 1i
The application context to use.
.SH RETURN VALUE
Nothing on success, else the process aborts.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
