.TH XTMISC_PROTO_ICON_FUNC 3 "13 Nov 2005" "Karma Distribution"
.SH PROTO_FUNC
xtmisc_PROTO_icon_func \- Write an icon pixmap.
.SH SYNOPSIS
.B #include <karma_xtmisc.h>
.sp
.B void xtmisc_PROTO_icon_func
.sp
(Display *display, Pixmap pixmap,
int width, int height)
.SH DESCRIPTION
Write an icon pixmap.
.IP \fIdisplay\fP 1i
The display pointer.
.IP \fIpixmap\fP 1i
The pixmap to write to.
.IP \fIwidth\fP 1i
The width of the pixmap.
.IP \fIheight\fP 1i
The height of the pixmap.
.SH RETURN VALUE
Nothing.
.SH Multi-threading Level
Unsafe.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
