.TH XV 3 "13 Nov 2005" "Karma Distribution"
.SH PACKAGE
xv \- Routines to query X visuals
.SH PURPOSE
These routines are meant to provide a convenience interface for querying
X visuals.
.SH LIBRARY
karmaX11
.SH LINK WITH
-lkarmaX11
.SH FUNCTIONS
.IP \fIxv_get_vinfos\fP 1i
Get supported visuals available on a screen.
.IP \fIxv_get_visuals\fP 1i
Get supported visuals available on a screen.
.IP \fIxv_get_visinfo_for_visual\fP 1i
Get the visual information structure for a visual.
.IP \fIxv_get_visinfo_for_visual2\fP 1i
Get the visual information structure for a visual.
.SH AUTHOR
Richard Gooch (rgooch@atnf.csiro.au)
.SH AVAILABLITY
The Karma Distribution is available for anonymous ftp from:

ftp://ftp.atnf.csiro.au/pub/software/karma/
ftp://wuarchive.wustl.edu/graphics/graphics/packages/karma/
ftp://ftp.pwr.wroc.pl/pub/karma/

The Karma Home Page is:

http://www.atnf.csiro.au/karma/
